/**
 * Event dataset, part 1: backstory and Volume 1.
 * Parts 2 and 3 append to the same array (window.MV_EVENTS).
 *
 * Fields
 *   id      unique key; also the deep-link hash and the illustration seed
 *   t       title
 *   d, e    ISO start date and optional end date (a span). Omitted on backstory events.
 *   pre     backstory order (1, 2, ...). Backstory sits before 1994 and is not to scale.
 *   when    date as displayed; approximate dates start with "c."
 *   basis   how the date was derived:
 *             "text"  given in the novel
 *             "real"  placed on the date of its real-world counterpart
 *             "est"   estimated from the chapter's time span
 *   vol, ch volume number and chapter label
 *   cat     finance | politics | deals | world | personal | shadow
 *   motif   illustration name (see art.js)
 *   fig     optional key figure shown on the illustration, e.g. "¥800bn"
 *   hist    relation to real history: real | altered | fiction | story
 *   brief   one or two sentences for cards and the hover preview
 *   what    bullet list: what happens
 *   reveal  bullet list: revelations (optional)
 *   real    real-world note (optional)
 *   sig     readings as [confidence, text]; confidence is s (strongly supported),
 *           p (plausible) or x (speculative)
 *   who     people involved
 *   links   ids of connected events
 *
 * build.js validates every field and reports unknown link ids.
 */
window.MV_EVENTS = (window.MV_EVENTS || []).concat([

/* ───────────── Backstory (not to scale) ───────────── */
{ id:"normandy", pre:1, t:"Normandy fails; Japan negotiates its surrender", when:"1944–45", basis:"text",
  vol:1, ch:"Ch. 2", cat:"world", motif:"war", hist:"altered",
  brief:"The Allies lose the Normandy landings and Germany fights on. Japan’s surrender is negotiated, so the peerage and the zaibatsu survive.",
  what:["The Allies lose at Normandy; Germany keeps fighting.","Japan surrenders on negotiated terms, then declares war on the Axis (Vol. 3 adds this), preserving many national interests.","The peerage is never abolished, the zaibatsu are never dissolved, and the Privy Council survives with its power suspended.","Nobles keep ‘impunity to arrest’ and a form of diplomatic immunity, which the glossary credits to Runa’s grandfather."],
  real:"Altered. In reality the Allies won at Normandy, Japan’s surrender was unconditional, and the peerage and zaibatsu were dissolved. The glossary states the divergence outright.",
  sig:[["s","This is the root divergence. Everything else follows from it: wealthier zaibatsu, a titled nobility, and a three-quarters-Russian protagonist produced by Cold War espionage."]],
  who:["Keikain Hikomaro"], links:["karafutocrisis","second226"] },

{ id:"daqing", pre:2, t:"Oil is struck in Manchuria, a decade early", when:"c. late 1940s", basis:"est",
  vol:1, ch:"Ch. 7", cat:"world", motif:"oil", hist:"altered",
  brief:"An American-backed Japanese speculator hits the Daqing field. Young Toudou throws him a box of Lucky Strikes moments before the well blows.",
  what:["Toudou, cut out of his zaibatsu’s inner clique, is sent to Heilongjiang because nobody with standing would go.","His mentor, known only as ‘the speculator’, stakes everything on a Manchurian field with American equipment. Iwazaki settles for a 30/70 joint venture.","The well blows. Covered in crude, the speculator laughs: ‘I did it! I really did it!’","Kuomintang forces, backed by the US and Japan, hold Manchuria and the Communists are driven out.","The speculator dies with nothing and leaves his daughter an empty Lucky Strikes box. Toudou later marries her."],
  reveal:["The alternate history extends beyond Japan: the Chinese Civil War diverged in Manchuria."],
  real:"Altered. Daqing was really discovered on 26 September 1959 by Chinese geologists, and the Communists took Manchuria in the 1948 Liaoshen Campaign. The novel reverses both.",
  sig:[["s","The empty box is the chapter’s thesis: fortune does not survive, but the memory of one self-made moment does."],["p","The speculator is a cautionary mirror for Runa. He had the genius and none of the protective structure she has in Tachibana and Ichijou."]],
  who:["Toudou Nagayoshi"], links:["akamatsu"] },

{ id:"karafutocrisis", pre:3, t:"The Karafuto Crisis: Northern Japan is founded", when:"c. early 1950s, during the Manchurian War", basis:"est",
  vol:3, ch:"Ch. 3", cat:"world", motif:"map", hist:"fiction",
  brief:"The USSR invades Japanese southern Karafuto and sets up the People’s Democratic Republic of Northern Japan. The partition is of Karafuto, not the home islands.",
  what:["Karafuto (Sakhalin) had been split after the Russo-Japanese War.","When Japan enters the Manchurian War, the USSR invades the Japanese south and installs a Soviet-aligned state with a Stasi-style Ministry of National Security.","The West wins the Manchurian War. The US defends Manchuria but acknowledges Northern Japan, to avoid nuclear war and to penalize Japan for its WWII surrender."],
  reveal:["This corrects an impression easily taken from Vol. 1: the home islands were never divided."],
  real:"Fictional, modeled on the German and Korean partitions. The ‘Manchurian War’ is the narration’s Korean War analogue.",
  sig:[["s","The account is given in Maefuji’s chapter. The man who arrests Runa in the game is the one who explains why her world exists."]],
  who:["Maefuji Shouichi"], links:["normandy","reunification","sniper"] },

{ id:"second226", pre:4, t:"The second February 26 Incident", when:"c. 1967", basis:"text",
  vol:2, ch:"Ch. 8", cat:"politics", motif:"diet", hist:"fiction",
  brief:"Literary figures call for a ‘Shōwa Restoration’. A battalion occupies central Tokyo and kills members of the nobility and the zaibatsu.",
  what:["An author’s call to overthrow the nobility and zaibatsu triggers a military uprising.","A battalion occupies central Tokyo and murders people linked to those classes.","The Imperial Police are disbanded afterward.","A memorial is held thirty-four years later, in 2001."],
  real:"Fictional. The real February 26 Incident was the 1936 coup attempt and had no sequel. The glossary says the idea is borrowed from Mamoru Oshii’s Kerberos Saga.",
  sig:[["p","It explains the nobility’s siege mentality, the ‘impunity to arrest’ privilege, and why nobles now lobby for arms and hire private military companies."]],
  who:[], links:["normandy","tower"] },

{ id:"cocom", pre:5, t:"The Far Eastern CoCom scandal and Otsumaro’s death", when:"c. late 1980s", basis:"est",
  vol:1, ch:"Ch. 2", cat:"shadow", motif:"document", hist:"altered",
  brief:"Runa’s father is caught diverting machine tools to Northern Japan. Protected from arrest by his blood, he dies by apparent suicide.",
  what:["Keikain Otsumaro built the Far Eastern Group with Russian émigré backing. It was a front for Eastern technology theft.","Machine tools are diverted to Northern Japan during the Sakata combine construction, a CoCom violation.","Otsumaro dies by apparent suicide. Secretary-General Katou used his own impunity to bury the collusion (Vol. 1 Ch. 4).","Tachibana tells Runa this history himself."],
  reveal:["Vol. 2 Ch. 7: it was Tachibana who pushed Otsumaro to suicide. Runa does not know."],
  real:"Altered. The glossary names the real 1987 Toshiba Machine/Kongsberg affair, in which milling machines sold to the USSR made submarine propellers quieter.",
  sig:[["x","Tachibana’s guilt gives him a permanent motive to manage what Runa learns, which makes him an unreliable source for everything told about her father."]],
  who:["Keikain Otsumaro","Tachibana Ryuuji","Katou Kazuhiro"], links:["tachibanahome","birth"] },

{ id:"reunification", pre:6, t:"The Winter Festival Revolution reunifies Karafuto", when:"c. 1990, after the Berlin Wall falls", basis:"est",
  vol:1, ch:"Ch. 8", cat:"world", motif:"news", hist:"fiction",
  brief:"Northern Japan’s secret police launch a coup during Maslenitsa with the army’s endorsement. Japan occupies Karafuto.",
  what:["The secret police use Maslenitsa festival security to launch a coup. Abroad it is called the Maslenitsa Revolution.","The secret-police chief defects and enables a largely peaceful reunification. His daughter is Shisuka Lydia.","Hokkaido ends up about 80% Japanese, 10% Russian and 10% Chinese. Former Northern citizens are treated as second-class."],
  real:"Fictional. Its shape follows German reunification after 1989, and the glossary invites comparison with a Korean division that actually ended.",
  who:["Shisuka Lydia"], links:["karafutocrisis","essays","karafutobank"] },

{ id:"birth", pre:7, t:"Keikain Runa is born", when:"c. 1990", basis:"est",
  vol:1, ch:"Ch. 2", cat:"personal", motif:"grave", hist:"story",
  brief:"A dead office worker wakes as the villainess of an otome game. Her mother, a Romanov honeytrap, dies soon after the birth.",
  what:["A modern office worker dies after their employer collapses and is reborn as Keikain Runa, villainess of ‘Love Where the Cherry Blossom Falls’.","Her mother, Natasha Alexandrovna Romanova, was a great-granddaughter of Tsar Alexander III, deployed by Northern Japan as a honeytrap.","As a toddler Runa confirms her identity with three tests and rules out being literally inside the game.","At the Sakata graves she lays white lilies and cries, wondering whether the tears are hers or ‘the real Keikain Runa’s’."],
  reveal:["Tachibana noticed her at two or three because the books she read were always reshelved correctly (Vol. 2 Ch. 7)."],
  real:"Story event. Tsar Alexander III is real; the Romanov descent is invented.",
  sig:[["s","She keeps full memory of the game and of real-world history. That foreknowledge is the premise of everything that follows."]],
  who:["Keikain Runa","Natasha Romanova","Tachibana Ryuuji"], links:["cocom","crash2008","ledgers"] },

/* ───────────── Volume 1 ───────────── */
{ id:"karafutobank", d:"1994-06-15", when:"1994", basis:"text",
  t:"Karafuto Bank is nationalized",
  vol:1, ch:"Ch. 6", cat:"world", motif:"news", hist:"fiction",
  brief:"In-world press: post-reunification Karafuto struggles with corruption and brain drain, and its former central bank is nationalized over bad debts.",
  what:["Karafuto Nippo and other papers report corruption, brain drain and bureaucratic dysfunction.","MITI intervenes. Iwazaki, Yodoyabashi and Futaki compete over the island’s resources.","Karafuto Bank, the former Northern Japanese central bank, is nationalized over bad debts."],
  real:"Fictional. Reported as newspaper extracts, with no narration.",
  sig:[["s","Documents inside the story carry the partition backstory without slowing the plot."]],
  who:[], links:["reunification","superj","combine"] },

{ id:"superj", d:"1995-06-15", when:"1995", basis:"text",
  t:"‘Super-J’ counterfeit yen appears",
  vol:1, ch:"Ch. 6", cat:"shadow", motif:"news", hist:"altered",
  brief:"A high-quality counterfeit yen note surfaces from the old Northern regime’s networks, against the backdrop of the Kobe earthquake and the Aum attacks.",
  what:["The Great Hanshin Earthquake and the Aum Shinrikyo incidents form the year’s backdrop.","‘Super-J’, a near-perfect counterfeit yen note, appears from the old regime’s residual networks."],
  real:"Altered. The glossary says Super-J is based on North Korea’s counterfeit dollar ‘supernotes’. The earthquake (17 Jan 1995) and the Aum attacks are real.",
  who:[], links:["karafutobank","kidnap"] },

{ id:"ledgers", d:"1995-04-20", when:"c. spring 1995", basis:"est",
  t:"A five-year-old asks for the secret ledgers", fig:"¥500m",
  vol:1, ch:"Ch. 2", cat:"finance", motif:"vault", hist:"story",
  brief:"Runa finds her household quietly shrinking, walks into Far Eastern Bank and demands the real books, ‘and the ones for your secret accounts too’.",
  what:["The household spends about ¥3m a month against income that has fallen from ¥5m to ¥3m. Aki needing a scholarship is the tell.","At the bank’s Tokyo branch Runa demands the true balance sheet and deflects refusal by announcing she is the family’s marriage asset.","She mortgages the estate for ¥500m against an appraisal near ¥1bn, deliberately leaving headroom.","Tachibana becomes guardian of record and branch manager Ichijou Susumu becomes her operator."],
  reveal:["Runa holds the economic exposure and the decisions. The adults hold the legal and reputational exposure."],
  real:"Story event, placed by the yen’s real 1995 high near ¥80 to the dollar, which is her entry point.",
  sig:[["s","Proxy control starts here as a clever workaround for a minor. Vol. 4’s Koizumi names it as the defect that makes her power illegitimate."]],
  who:["Keikain Runa","Ichijou Susumu","Tachibana Ryuuji"], links:["moonlight","qualified"] },

{ id:"moonlight", d:"1995-05-15", e:"1997-02-15", when:"c. 1995 – early 1997", basis:"est",
  t:"The Moonlight Fund turns ¥500m into ¥50bn", fig:"¥50bn",
  vol:1, ch:"Ch. 2", cat:"finance", motif:"chartup", hist:"story",
  brief:"An offshore fund stacks a US browser IPO, an IT basket and a yen trade bought near ¥80 to the dollar. She closes out when the yen passes ¥120.",
  what:["Three legs: a US browser-company IPO (about $100m), an IT basket (about $100m), and FX bought at ¥80/$ and unwound toward ¥100/$.","The equity gain and the currency gain compound on the same position.","Collateral is Far Eastern Life Insurance’s assets, borrowed against at a ‘Japan premium’.","When the yen passes ¥120 she cancels her positions to lock in profit.","The Ministry of Finance notices a lender behaving like a trading desk, and Runa has to lie low."],
  real:"The ¥80/$ high of 1995, the dot-com run-up and the Japan premium are real. The trade itself is fiction and assumes foreknowledge with no slippage.",
  sig:[["s","Borrowing at a penalty rate for a directional bet is rational only with extraordinary conviction. Foreknowledge supplies it."],["p","Using a life insurer’s assets to fund speculation is a textbook conflict inside a financial conglomerate."]],
  who:["Keikain Runa","Ichijou Susumu"], links:["ledgers","fareastern","browser"] },

{ id:"kindergarten", d:"1996-05-20", when:"c. 1996", basis:"est",
  t:"Kindergarten: Asuka, Hotaru and the Pine Corridor brawl",
  vol:1, ch:"Ch. 3", cat:"personal", motif:"school", hist:"story",
  brief:"Runa insists on kindergarten over the family’s wish to hide her. She meets Asuka and Hotaru, and fights the boys who mock Mio’s doll.",
  what:["The main family wants her isolated, ostensibly over her blonde hair and actually over her father’s scandal.","She meets Kasugano Asuka, a Dietman’s daughter from Ehime who insists mandarins are ‘oranges’.","She meets Kaihouin Hotaru, who cannot be found at hide-and-seek, even on video.","Boys mock Amane Mio for needing her doll and a brawl follows: the ‘Incident of the Pine Corridor’."],
  real:"Story event. The glossary confirms the 1991 beef and orange import liberalization that the Kasugano family opposed.",
  who:["Kasugano Asuka","Kaihouin Hotaru","Amane Mio"], links:["dollhouse","essays"] },

{ id:"fareastern", d:"1996-10-15", when:"c. late 1996", basis:"est",
  t:"The Far Eastern Group is restructured", fig:"¥30bn",
  vol:1, ch:"Ch. 2", cat:"deals", motif:"merge", hist:"story",
  brief:"Runa carves out the hotels, lets the property arm fail on purpose and buys a third of the bank: a pre-packaged bankruptcy.",
  what:["The Moonlight Fund buys Far Eastern Hotels for ¥30bn before the property arm files.","Far Eastern Developments repays down to ¥15bn and files for corporate rehabilitation at the Yamagata District Court.","The bank writes off the rest from trading profits.","The remaining ¥20bn buys a 33% stake in Far Eastern Bank."],
  real:"Fictional group, real technique: extract value, isolate the loss in a shell, plug the hole with outside capital, acquire the reorganized whole.",
  sig:[["p","Far Eastern Developments is a jusen in miniature. Runa’s first rescue is a scale model of the problem that broke Japan."],["p","A generous related-party transfer just before filing is what a real trustee would attack."]],
  who:["Keikain Runa","Ichijou Susumu"], links:["moonlight","sankai"] },

{ id:"schoolday", d:"1997-04-08", when:"c. April 1997", basis:"est",
  t:"First day of school: a message to her future self",
  vol:1, ch:"Ch. 3", cat:"personal", motif:"school", hist:"story",
  brief:"On home video, child-Runa records a message asking her future self whether she is happy. The battery dies.",
  what:["Home video of her first day at Imperial Gakushuukan Academy.","She records a message to her future self asking if she is happy.","The battery dies mid-recording."],
  sig:[["s","Chapter 1 has already answered the question. The warmth she builds is what makes 2008 land as loss."]],
  who:["Keikain Runa"], links:["crash2008","quartet"] },

{ id:"debut", d:"1997-05-24", when:"c. spring 1997", basis:"est",
  t:"The debut party: Runa names her father’s scandal",
  vol:1, ch:"Ch. 3", cat:"personal", motif:"crown", hist:"story",
  brief:"At her Keikain debut she mentions the scandal in front of the Duke, on purpose. Katou meets her with visible emotion, and she meets Teia Eiichi.",
  what:["She references her father’s scandal before Duke Kiyomaro, turning apparent naïveté into leverage.","Secretaries arrive from Finance Minister Izumikawa and Secretary-General Katou. Katou’s district is Sakata.","Nakamaro asks Teia Eiichi to befriend her. She teaches him vending machines and cola, echoing a game scene.","At the Keika Group’s fiftieth anniversary she overhears talk of ‘the girl who dreamt up Keika Bank’ and learns Iwazaki is circling."],
  reveal:["She begins to suspect her downfall is a political purge of Far Eastern associates, not a romantic betrayal."],
  real:"Story event. Katou Kazuhiro maps to Katō Kōichi; Iwazaki maps to Mitsubishi.",
  who:["Keikain Kiyomaro","Katou Kazuhiro","Teia Eiichi","Keikain Nakamaro"], links:["quartet","engagement","iwazakirefuse"] },

{ id:"sankai", d:"1997-06-15", when:"June 1997", basis:"text",
  t:"Sankai Securities bought under the ‘Keika Rules’", fig:"¥80bn",
  vol:1, ch:"Ch. 2", cat:"finance", motif:"bank", hist:"altered",
  brief:"The first rung of the ladder. Runa takes the smallest failing broker and, with it, a live Bank of Japan special loan.",
  what:["Sankai carries ¥80bn in bad debt. The ministry’s own securities division had already failed to fix it.","The Keika Rules: dismiss the executives, punish malpractice, send all bad loans to the RCC, reduce capital, issue new shares to a third party, take a BOJ special loan.","Buying Sankai acquires the thing that matters: an existing claim on the state’s safety net."],
  real:"Altered. Sankai is Sanyo Securities, which really failed on 3–4 November 1997, the first postwar failure of a securities firm. Here it is rescued months earlier.",
  sig:[["s","The rules are a good-bank/bad-bank resolution with a bail-in of equity, the architecture real resolution authorities use."],["s","Nobody walks into the ministry and asks for trillions. Each rung buys credibility for the next."]],
  who:["Keikain Runa","Ichijou Susumu"], links:["fareastern","ichiyama","memoir"] },

{ id:"quartet", d:"1997-07-20", when:"c. July 1997", basis:"est",
  t:"The Gakushuukan Quartet forms",
  vol:1, ch:"Ch. 3", cat:"personal", motif:"tea", hist:"story",
  brief:"Runa meets Yuujirou at an adult qualification exam and Mitsuya in a café over a shared book. With Eiichi, they become the Quartet.",
  what:["She meets Izumikawa Yuujirou at an exam hall where both elementary schoolers are sitting adult certifications.","Gotou Mitsuya is recruited at a café over a shared book.","With Teia Eiichi, the four become ‘the Gakushuukan Quartet’."],
  reveal:["She is knowingly assembling the people who will denounce her, and chooses warmth anyway."],
  real:"Story event. The chapter is dated by Princess Mononoke’s July 1997 release.",
  sig:[["s","Building affection for her eventual accusers makes Chapter 1 land as loss, not comeuppance."]],
  who:["Teia Eiichi","Izumikawa Yuujirou","Gotou Mitsuya"], links:["debut","avanti","crash2008"] },

{ id:"pudding", d:"1997-07-30", when:"c. summer 1997", basis:"est",
  t:"Naoyuki’s plea and the pudding lesson", fig:"¥9,900",
  vol:1, ch:"Ch. 2", cat:"finance", motif:"tea", hist:"story",
  brief:"Katsura Naoyuki begs her to save Hokkaido Kaitaku Bank. Ichijou explains bad debt with a ¥100 coin and Aki’s homemade pudding.",
  what:["Naoyuki works in the very department sinking Hokkaido Kaitaku and prostrates himself. Runa sends ¥100m at once.","Her anger at ‘an era that created a society that wouldn’t reward even the hardest of efforts’ turns her into an active interventionist.","Ichijou’s lesson: money has value because it is perceived to, on the guarantee of a third party.","Runa sells a pudding for ¥10,000 and buys it back at ¥100. The ¥9,900 gap is the non-performing loan."],
  real:"Story event. The lesson is a compressed statement of the credit theory of money.",
  sig:[["s","The pudding dramatizes a bubble instead of explaining one: book value and market value diverge."],["p","Naoyuki’s stake converts macro-finance into something personal."]],
  who:["Katsura Naoyuki","Ichijou Susumu","Tokitou Aki"], links:["kaitaku","sme"] },

{ id:"ichiyama", d:"1997-08-20", when:"c. August 1997", basis:"est",
  t:"Ichiyama merged into Sankai: the reverse merger", fig:"¥260bn",
  vol:1, ch:"Ch. 2", cat:"finance", motif:"merge", hist:"altered",
  brief:"The larger, scandal-ridden broker is folded into the smaller one so that Sankai’s special loan survives and Ichiyama’s hidden losses can be reset.",
  what:["Ichiyama hides ¥260bn in a tobashi scheme and has paid off corporate bouncers, so it cannot get a BOJ special loan directly.","It merges into the smaller Sankai. The survivor takes the assets at current market value.","Both safety nets are inherited and the residue goes to the Resolution and Collection Corporation.","Tachibana plays the ministry’s divisions against each other: no division wants the failure on its watch."],
  real:"Altered. Ichiyama is Yamaichi Securities, which announced its closure on 24 November 1997 after hiding about ¥260bn in tobashi losses. The payoffs match the 1997 Koike sōkaiya scandal.",
  sig:[["s","The reverse merger exists because of the sōkaiya scandal. The payoff and the tobashi are one culture of manipulated client accounts."],["s","Press attention fixes on the legible villain and never examines the structure beneath."]],
  who:["Keikain Runa","Tachibana Ryuuji"], links:["sankai","kaitaku","mofscandal"] },

{ id:"matsuno", d:"1997-09-25", when:"c. autumn 1997", basis:"est",
  t:"Toudou joins; Matsuno Trading is bailed out", fig:"¥180bn",
  vol:1, ch:"Ch. 4", cat:"deals", motif:"oil", hist:"story",
  brief:"A resources man with a Manchurian past becomes Runa’s advisor, and the Fund buys up a trading company’s loans from its banks.",
  what:["Toudou Nagayoshi joins and points to gas and oil tied to Karafuto and Sakata.","Runa moves assets into Swiss private banking.","Katou is revealed as complicit in the cover-up that destroyed her father. His backing for Sakata now reads as atonement.","The Moonlight Fund buys ¥180bn of Matsuno Trading’s loans and intervenes in its management."],
  reveal:["Meeting Runa, Toudou sees the speculator’s smile and reaches for a cigarette before stopping himself."],
  real:"Story event. Matsuno later merges with Akamaru, which echoes Marubeni.",
  who:["Toudou Nagayoshi","Katou Kazuhiro"], links:["daqing","akamatsu"] },

{ id:"kaitaku", d:"1997-10-28", when:"c. autumn 1997", basis:"est",
  t:"Takeover bid for Hokkaido Kaitaku Bank at ¥74", fig:"¥2.3tn",
  vol:1, ch:"Ch. 2", cat:"finance", motif:"bank", hist:"altered",
  brief:"Runa waits for the shares to hit ¥59, then bids ¥74 through a ‘California-based’ fund fronted by a real American lawyer.",
  what:["Hokkaido Kaitaku carries ¥2.3tn in bad debt.","She waits until failure is near-certain (¥59 a share) and bids ¥74.","The bid comes from the ‘California-based Moonlight Fund’, fronted at a press conference by a lawyer-actor whose credentials survive checking.","The spokesman ad-libs that the owner has Russian blood. Runa ‘didn’t know then the full impact’ of that line."],
  reveal:["Runa believes she has broken the chain reaction: ‘At least, that was what I believed at the time.’"],
  real:"Altered, and the novel’s first major divergence. Hokkaido Takushoku Bank really failed on 17 November 1997, the first postwar city-bank failure. Its shares fell to ¥65.",
  sig:[["s","The convoy system survives 1997 in this timeline because Runa becomes its last escort ship."],["s","Buying equity in a bank with ¥2.3tn of holes is an entry ticket to the negotiating table, not a rescue."]],
  who:["Keikain Runa","Katsura Naoyuki"], links:["ichiyama","keikabank","kidnap"] },

{ id:"browser", d:"1997-11-11", when:"11 November 1997", basis:"text",
  t:"The browser company lists: ‘I made it’", fig:"¥2m/share",
  vol:1, ch:"Ch. 2", cat:"finance", motif:"chartup", hist:"altered",
  brief:"The newly listed ‘browser company’ opens at ¥2m a share. Runa steps into the garden and says: ‘I made it.’",
  what:["The Japanese arm of the US browser company lists and opens at ¥2m a share.","By February 2000 it reaches ¥167.9m a share.","Ichijou becomes a corporate officer and Naoyuki moves to private banking."],
  real:"Altered. It closely tracks Yahoo! Japan, which listed in November 1997 and in January 2000 became the first Japanese stock above ¥100m a share.",
  who:["Keikain Runa"], links:["moonlight","tig"] },

{ id:"keikabank", d:"1997-12-05", when:"c. late 1997", basis:"est",
  t:"Keika Bank is formed, and Runa signs away control", fig:"¥8tn",
  vol:1, ch:"Ch. 2", cat:"finance", motif:"bank", hist:"altered",
  brief:"Four banks become Keika Bank on about ¥8 trillion of BOJ special loans. Runa declines management in exchange for a written right to bid later.",
  what:["When Keika Group funding is exposed in the Diet, the merged bank is renamed Keika Bank.","LPCB and Nihon Credit Bank follow under the same protocol. BOJ special loans approach ¥8tn and commentators call it effective nationalization.","Runa declines the right of management: ‘do you think I look like I know how to run one of Japan’s largest banks?’","In return she gets a memorandum: the right to bid when the bank is privatized, plus guaranteed equity."],
  real:"Altered. LPCB and Nihon Credit are the Long-Term Credit Bank and Nippon Credit Bank, really nationalized in October and December 1998. BOJ special loans are real; ¥8tn to one group strains belief.",
  sig:[["s","The memorandum is a call option on the Japanese banking system, with the state funding the cleanup between grant and exercise."],["s","After the Jusen backlash, public money for banks was poison. Runa brought private money, and that gap is the space her empire is built in."]],
  who:["Keikain Runa","Ichijou Susumu"], links:["kaitaku","auction","memoir"] },

{ id:"teisei", d:"1997-12-18", when:"c. winter 1997–98", basis:"est",
  t:"The Teisei rescue and the ‘Little Queen’ campaign", fig:"¥1.75tn",
  vol:1, ch:"Ch. 8", cat:"deals", motif:"crown", hist:"altered",
  brief:"With DK Bank paralyzed, Keika Bank saves Teisei Department Stores. A winter ad shoot puts Runa on a throne and gives her a nickname.",
  what:["Teisei carries about ¥1.75tn in bad debts from a bubble-era move into hotels and real estate.","Its main bank, DK Bank, is paralyzed by threats from corporate bouncers, leaving Keika Bank the only savior.","A shopping trip becomes the winter campaign shoot: Runa as a queen on a throne with a pocket watch.","The campaign works and the nickname ‘Little Queen’ sticks."],
  real:"Altered. DK Bank is Dai-Ichi Kangyo Bank, which the ministry really barred from new lending for five months in 1997 over the Koike sōkaiya scandal.",
  sig:[["p","Politicians later use the nickname. Izumikawa calls her ‘Your Little Majesty’ and ‘small kingmaker’."]],
  who:["Keikain Runa"], links:["akamatsu","sougou","governor"] },

{ id:"kidnap", d:"1998-01-10", when:"c. winter 1997–98", basis:"est",
  t:"Kidnapped at the Keika Holdings launch party",
  vol:1, ch:"Ch. 4", cat:"shadow", motif:"spy", hist:"story",
  brief:"Runa is drugged and taken at a boat party. The three boys answer with an improvised wiretap and a smoke device, alongside a Public Safety raid.",
  what:["The party announces Keika Holdings, Japan’s first new-style bank holding company.","A doctor employed by a debt-ridden Keika-linked firm drugs her, helped by a bribed guard.","Eiichi, Yuujirou and Mitsuya intervene personally alongside a raid led by Inspector Maefuji Shouichi.","Nakamaro publicly strikes Maefuji, a staged cover story to bury the sensitive facts under a simpler one."],
  reveal:["Maefuji is the officer who arrests Runa at the game’s climax. She arranged for the boys to witness his visit, hoping to change their future reaction.","Vol. 1 Ch. 9: a Russian oligarch ordered it, wanting her Romanov-linked fortune."],
  real:"Story event. The Public Safety Bureau is described as the postwar successor to the Special Higher Police.",
  sig:[["s","The Romanov claim is a live geopolitical liability, set off by one ad-libbed line at a press conference."]],
  who:["Maefuji Shouichi","Teia Eiichi","Izumikawa Yuujirou","Gotou Mitsuya","Keikain Nakamaro"], links:["kaitaku","russia","protection"] },

{ id:"mofscandal", d:"1998-01-28", when:"28 January 1998", basis:"real",
  t:"The Finance Ministry scandal; Izumikawa resigns",
  vol:1, ch:"Ch. 4", cat:"politics", motif:"document", hist:"real",
  brief:"A payoff to a corporate bouncer unravels into ministry corruption. Officials resign, some die by suicide, and Finance Minister Izumikawa steps down.",
  what:["The corruption starts from a payoff to a corporate bouncer and exposes a bank intermediary and a ministry bureaucrat.","The BOJ governor and ministry officials resign. Izumikawa resigns to take responsibility.","Runa deduces that the Public Safety Bureau permitted or engineered the crisis to strip the ministry of power."],
  real:"Real, with the motive altered. This is the 1998 ‘no-pan shabu-shabu’ bribery scandal. Izumikawa’s resignation is Finance Minister Mitsuzuka Hiroshi’s, on 28 January 1998.",
  sig:[["s","A real bureaucratic collapse is reframed as secretly accelerated by the security state. The why changes; the timeline does not."]],
  who:["Izumikawa Tatsunosuke"], links:["ichiyama","election98","taichirou"] },

{ id:"valentine", d:"1998-02-14", when:"14 February 1998", basis:"text",
  t:"The five-yen Valentine’s puzzle", fig:"¥5",
  vol:1, ch:"Ch. 8", cat:"personal", motif:"tea", hist:"story",
  brief:"Instead of an expensive gift, Runa designs an economics riddle around a tiny five-yen base present.",
  what:["Runa builds a Valentine’s gift around a five-yen base and a riddle.","The arc runs through White Day.","A stargazing scene shows Yuujirou outside the political-heir persona."],
  real:"Story event. The year is inferred from the chapter.",
  sig:[["s","The series teaches economics through objects: the coin and the pudding, then this."]],
  who:["Izumikawa Yuujirou"], links:["pudding","concert"] },

{ id:"engagement", d:"1998-02-25", when:"c. early 1998", basis:"est",
  t:"The engagement is calculated",
  vol:1, ch:"Ch. 5", cat:"personal", motif:"merge", hist:"story",
  brief:"In the book’s first shift of viewpoint, the Duke weighs marrying Runa to Eiichi, Yuujirou or Mitsuya. Nakamaro remembers a promise.",
  what:["Kiyomaro and Nakamaro discuss Runa as a strategic marriage asset and list each match’s trade-offs.","As a child Nakamaro met Natasha and promised her, as she was dying, to protect her daughter.","Nakamaro accepts his own political marriage to a marquess’s daughter tied to Iwazaki."],
  reveal:["Nakamaro’s warmth is the discharge of a deathbed promise, not family duty."],
  sig:[["s","The reader sees the deliberations Runa cannot."],["p","If Runa falls, Nakamaro fails Natasha."]],
  who:["Keikain Kiyomaro","Keikain Nakamaro"], links:["debut","proposal","testimony","crash2008"] },

{ id:"combine", d:"1998-03-15", when:"1998", basis:"text",
  t:"The Karafuto gas combine is announced",
  vol:1, ch:"Ch. 6", cat:"deals", motif:"oil", hist:"fiction",
  brief:"Ishikari Bay, Sakata and Niigata are tied into a Karafuto gas project with Iwazaki, Yodoyabashi and Keika’s Matsuno Trading.",
  what:["The combine links Ishikari Bay, Sakata and Niigata.","Hong Kong Handover refugees settle in Karafuto, forming a Cantonese-speaking community tied to a Russian-mafia laundering network.","Vol. 1 Ch. 9 clarifies the Sakata side: it converts the Fund’s dollar profits into yen through oil-stockpiling arbitrage."],
  real:"Fictional project. The Hong Kong Handover is real.",
  who:["Toudou Nagayoshi"], links:["matsuno","akamatsu","trustaccount"] },

{ id:"concert", d:"1998-04-18", when:"c. spring 1998", basis:"est",
  t:"The concert: Runa sings Micaëla’s aria",
  vol:1, ch:"Ch. 8", cat:"personal", motif:"stage", hist:"story",
  brief:"In the Teia family’s box for Bizet’s suites, Runa casts the heroine as Carmen and sings the losing fiancée’s aria to Eiichi.",
  what:["Eiichi, who hates classical music, begs her to sit with him. Tachibana has a dress ready.","Runa calls Carmen and L’Arlésienne ‘irredeemable tales’ undone by a bright, lively style.","She says it is ‘even more interesting when you know the historical context’.","Asked her favorite, she sings ‘Nocturne’, Micaëla’s aria. The orchestra joins and the audience takes it for an encore."],
  real:"The suites are real and correctly placed. One slip: Runa says Carmen’s appeal came from her Basque heritage, but in Mérimée it is José who is Basque.",
  sig:[["s","Bright surface, irredeemable content: the scene states the novel’s own aesthetic."],["s","At eight she sings the arranged fiancée’s aria to the man she expects to lose. In the opera, Micaëla fails."],["s","Later volumes show the Carmen triangle is a misreading. The ruin is financial."]],
  who:["Teia Eiichi","Tachibana Ryuuji"], links:["queennight","dream","downfall"] },

{ id:"akamatsu", d:"1998-05-12", when:"c. spring 1998", basis:"est",
  t:"Akamatsu Corporation is formed",
  vol:1, ch:"Ch. 9", cat:"deals", motif:"merge", hist:"story",
  brief:"Matsuno Trading, Akamaru and Keika Corp merge into a trading house under Toudou, with Teisei as its subsidiary and a rescued airline alongside.",
  what:["Runa watches the Keika Bank board by monitor and speaks into Ichijou’s earpiece.","A trading company is installed over Teisei as ‘the blood vessels and nervous system’ between Hokkaido producers, the bank and retail.","Toudou becomes managing director.","AIRHO, a struggling Hokkaido low-cost airline, is rescued with cheap Boeing 737-700ERs bought amid Asian-crisis cancellations."],
  real:"Story event. Akamaru echoes Marubeni. The Asian currency crisis is real.",
  who:["Toudou Nagayoshi","Ichijou Susumu"], links:["matsuno","teisei","arms","saudi"] },

{ id:"dollhouse", d:"1998-05-23", when:"c. spring 1998", basis:"est",
  t:"The dollhouse",
  vol:1, ch:"Ch. 8", cat:"shadow", motif:"dollhouse", hist:"story",
  brief:"Runa and Mio are drawn into a dreamlike dollhouse with faceless but warm parents. Hotaru pulls them out, smiling. It is never found again.",
  what:["Runa and Mio enter a dollhouse with faceless, warm parent figures.","Hotaru extracts them and reacts with a knowing, mischievous smile.","Runa buys antique dolls to prop up Mio’s father’s trading company and lends them to a Teisei exhibition he hosts."],
  reveal:["Hotaru was originally meant to be ritually sacrificed to become a zashiki warashi."],
  real:"Story event. Zashiki warashi are real household spirits of Japanese folklore.",
  sig:[["s","A mundane mystery (the librarian who always finds Hotaru) sits beside one the book declines to explain."],["p","The supernatural layer may point at the nature of the reincarnation itself."]],
  who:["Kaihouin Hotaru","Amane Mio"], links:["kindergarten","fortune","downfall"] },

{ id:"essays", d:"1998-06-10", when:"c. mid-1998", basis:"est",
  t:"School essays, and Lydia ‘Vasilisa’",
  vol:1, ch:"Ch. 8", cat:"personal", motif:"school", hist:"story",
  brief:"Asuka writes of an arranged future. Runa meets Shisuka Lydia, whose father’s defection made reunification possible.",
  what:["Asuka’s essay accepts an arranged marriage and an inherited Diet seat.","Shisuka Lydia is an upperclassman of mixed Russian and Japanese-noble heritage, ostracized as Runa is.","Her father, former head of Northern Japan’s secret police, is honored by Japan and hated by Karafuto natives.","The class discusses Kajii, Dazai, Akutagawa and Niimi Nankichi."],
  real:"Story event. The literature is real and accurately summarized.",
  sig:[["p","Lydia is a structural mirror: a legacy that is heroic and treasonous at once."]],
  who:["Shisuka Lydia","Kasugano Asuka"], links:["reunification","downfall"] },

{ id:"taichirou", d:"1998-06-20", when:"c. June 1998", basis:"est",
  t:"Taichirou is moved to the party list", fig:"¥10bn",
  vol:1, ch:"Ch. 9", cat:"politics", motif:"ballot", hist:"story",
  brief:"Yuujirou’s brother faces defeat in a two-seat district. Runa bargains him onto the proportional list for about ¥10bn.",
  what:["Two ruling-party candidates from rival factions split one two-seat district, and Taichirou is bleeding supporters.","Secretary-General Katou, poaching the Izumikawa faction, will decide on endorsement ‘after the election’.","Runa has him withdraw and run on the proportional list, where rank decides everything.","She bargains with Katou using Sakata’s oil reserves and Keika’s support. Yuujirou whispers: ‘Thank you, Keikain-san.’"],
  real:"Story event on real mechanics: the 1998 upper-house list was a single closed national list ranked by party headquarters.",
  sig:[["p","It is her first deliberate rewrite of a love interest’s family fate, done by translating friendship into obligation."],["p","About ¥10bn on one candidate far exceeds legal campaign limits. The book never explains the route."]],
  who:["Izumikawa Taichirou","Izumikawa Yuujirou","Katou Kazuhiro"], links:["mofscandal","election98"] },

{ id:"angela", d:"1998-07-04", when:"c. early July 1998", basis:"est",
  t:"Angela Sullivan’s visit and the bubuzuke",
  vol:1, ch:"Ch. 9", cat:"shadow", motif:"spy", hist:"story",
  brief:"A CIA officer posing as a fund manager warns Runa off the Keika Bank auction. Runa serves her the Kyoto signal to leave.",
  what:["Angela poses as a manager at the Pacific Global Investment Fund.","She hints at ECHELON and reveals the CIA has watched Runa since her parents’ collusion.","She warns her off the auction.","Runa serves bubuzuke, the Kyoto signal to leave. Angela leaves it untouched."],
  reveal:["Runa realizes this is probably how the game’s villainess became ‘a former eastern spy’ involved in a takeover of Teia Motor."],
  real:"Story event. ECHELON is real.",
  who:["Angela Sullivan"], links:["sullivan","tachibanahome","auction"] },

{ id:"election98", d:"1998-07-12", when:"12 July 1998", basis:"real",
  t:"The 1998 upper-house election: the ruling party is routed",
  vol:1, ch:"Ch. 9", cat:"politics", motif:"ballot", hist:"real",
  brief:"The ruling party is heavily defeated and the Prime Minister resigns. Taichirou wins ‘the final space’ on the party list.",
  what:["The ruling party suffers a heavy defeat and the Prime Minister resigns.","Taichirou is the party’s last list winner, elected at the margin.","Runa learns what she averted: a succession war in his family ‘just like they did in the game’, and his father leaving politics.","Katou later resigns over the defeat and Hayashi becomes Secretary-General."],
  real:"Real. In the election of 12 July 1998 the LDP won 44 seats against the 61 it held, and Hashimoto resigned on election night. Katō Kōichi took the blame.",
  who:["Izumikawa Taichirou","Katou Kazuhiro"], links:["taichirou","fuchigamipm"] },

{ id:"fuchigamipm", d:"1998-07-30", when:"30 July 1998", basis:"real",
  t:"Fuchigami becomes Prime Minister; a scribbled note makes Izumikawa vice president",
  vol:1, ch:"Ch. 9", cat:"politics", motif:"diet", hist:"altered",
  brief:"During a tense phone call Runa silently directs Izumikawa with a note. Koizumi loses the leadership race and starts to see her as an opponent.",
  what:["Foreign Minister Fuchigami Keiichi becomes Prime Minister.","Runa directs Dietman Izumikawa by scribbled note to demand, and win, the party vice presidency.","Koizumi Souichirou stands for leader and loses badly. His sworn friend Katou used the reshuffle for a higher post.","Hayashi tells Koizumi who pulled the strings: ‘the Keika girl, that Little Queen.’"],
  reveal:["Koizumi and Runa will confront each other directly ‘around two years later’."],
  real:"Altered. Fuchigami is Obuchi Keizō, who won the LDP presidency on 24 July 1998 and became PM on 30 July. Koizumi’s defeat is real. Izumikawa’s vice presidency is fiction.",
  who:["Fuchigami Keiichi","Izumikawa Tatsunosuke","Koizumi Souichirou"], links:["election98","stroke","koizumiwins"] },

{ id:"russia", d:"1998-08-17", when:"17 August 1998", basis:"real",
  t:"Russia defaults. Runa saw it coming and warned no one",
  vol:1, ch:"Ch. 9", cat:"finance", motif:"chartcrash", hist:"real",
  brief:"Runa foresees the Russian crisis and the hedge-fund losses to follow, and stays silent. Her rivals for Keika Bank are about to be crippled.",
  what:["Maefuji all but confirms that a Russian oligarch, a former Soviet gas minister, ordered her kidnapping.","Runa foresees the Russian financial crisis and the American hedge-fund losses.","She chooses not to warn anyone and accepts the moral cost.","The kidnappers’ hedge fund had rated a Russian default at ‘three in a million’."],
  real:"Real. Russia defaulted on 17 August 1998.",
  sig:[["s","The payoff of her option depends on her silence."],["s","Her 1998 silence, from which she profits, and her 2003 refusal to short subprime are the same character at two points in her arc."]],
  who:["Keikain Runa","Maefuji Shouichi"], links:["kidnap","auction","subprimerefusal"] },

{ id:"auction", d:"1998-09-20", when:"20 September 1998", basis:"text",
  t:"Sole bidder: Keika Bank is bought for ¥800bn", fig:"¥800bn",
  vol:1, ch:"Ch. 9", cat:"finance", motif:"bank", hist:"altered",
  brief:"The Moonlight Fund wins the privatized Keika Bank as the only bidder, because ‘America was too busy trying to bail out its large-scale hedge fund’.",
  what:["Runa exercises the memorandum she took in Chapter 2.","There is no bidding war: ‘there weren’t enough players for that.’","The bid is financed by domestic banks the ministry ‘urged’ to lend.","Her own narration still frames the victory as a step along a path of ruin."],
  real:"Altered. The real sales of the nationalized LTCB (to Ripplewood) and NCB came in 2000. The novel moves them to September 1998 and lets the Japanese bidder win.",
  sig:[["s","Chapters 2 and 9 are one financial structure: an option written in 1997 and exercised in 1998."],["p","Ripplewood got a government-written put on LTCB’s bad loans. Runa got a government-written call on the cleaned-up bank."]],
  who:["Keikain Runa","Ichijou Susumu"], links:["keikabank","russia","ltcm","sullivan"] },

{ id:"ltcm", d:"1998-09-23", when:"23 September 1998", basis:"real",
  t:"Wall Street rescues its giant hedge fund", fig:"$3.625bn",
  vol:1, ch:"Ch. 9", cat:"finance", motif:"chartcrash", hist:"real",
  brief:"Days after the auction, a consortium bails out the ‘large-scale hedge fund’. The glossary ties it directly to Lehman.",
  what:["The fund’s bailout involves ‘government guidance just like that given out by the Ministry of Finance’.","The glossary: ‘The failure to learn from this disaster is what led to the situation with Lehman Brothers.’","In Vol. 2, Angela is exhausted from ‘cleaning up after that collapsed Wall Street fund’."],
  real:"Real. This is LTCM: on 23 September 1998 fourteen firms put up $3.625bn for 90% of the fund in a Fed-brokered deal with no Fed money.",
  sig:[["s","Administrative guidance in two countries in one week: the ministry urges banks to lend to Runa while the Fed persuades banks to rescue LTCM."],["s","The frame scene’s Lehman opening completes a real historical argument."]],
  who:["Angela Sullivan"], links:["auction","crash2008","subprime"] },

{ id:"moscow", d:"1998-11-12", when:"c. November 1998", basis:"real",
  t:"The Moscow Declaration: a loan repaid in crude",
  vol:1, ch:"Ch. 9", cat:"world", motif:"oil", hist:"altered",
  brief:"Fuchigami signs a partnership declaration in Russia, with a syndicated loan funded mainly by the Moonlight Fund and repayable in oil.",
  what:["PM Fuchigami signs a ‘Moscow Declaration on Establishing a Creative Partnership’.","A syndicated loan repayable in crude oil is funded mainly by the Moonlight Fund.","The oligarch’s refusal to contribute fuels rumors about repayment."],
  real:"Altered. It mirrors the real November 1998 Obuchi–Yeltsin declaration (not re-verified). The Fund’s role is fiction.",
  sig:[["s","Runa’s private finance is folded into state diplomacy."]],
  who:["Fuchigami Keiichi"], links:["russia","trustaccount","coup"] }
]);
