/** Event dataset, part 2: Volume 2 (autumn 1998 to April 2001). Field reference: events_1.js. */
window.MV_EVENTS = (window.MV_EVENTS || []).concat([

{ id:"sullivan", d:"1998-10-10", when:"c. autumn 1998", basis:"est",
  t:"The Sullivan Report", fig:"¥3tn",
  vol:2, ch:"Ch. 1", cat:"shadow", motif:"document", hist:"story",
  brief:"A CIA dossier names Runa as the real owner of the Moonlight Fund and recommends procuring her as a US asset. One section is marked [OMITTED].",
  what:["Angela Sullivan’s assessment maps the whole post-auction corporate structure.","Keika Bank, bought for ¥800bn, is now said to be worth over ¥3tn.","The Keika Group’s main bank is still the Imperial Iwazaki Bank, not Keika Bank.","Runa has made no move on the Keika Group ‘out of respect for her uncle’.","Recommendation: keep monitoring and find a way to procure her as an asset."],
  reveal:["The CIA knows everything material. Vol. 1’s secrecy is over."],
  real:"Story event, told as a pure document with no narration.",
  sig:[["s","Vol. 1 opened inside Runa’s head. Vol. 2 opens in a foreign intelligence file. The reader moves from confidant to observer."],["p","The [OMITTED] marker is a reminder that nobody in this book has complete information."]],
  who:["Angela Sullivan"], links:["angela","auction","tachibanahome"] },

{ id:"fieldday", d:"1998-10-18", when:"c. October 1998", basis:"est",
  t:"Field day: the three-legged race and the relay",
  vol:2, ch:"Ch. 4", cat:"personal", motif:"school", hist:"story",
  brief:"Runa and Eiichi fall flat in the three-legged race. In the relay she takes her team from last to first.",
  what:["Runa and Eiichi fall immediately. Mitsuya: ‘a prime example of what happens when two partners are both in it for themselves.’","In the final relay she invokes the frame: ‘I was born a villainess. I would lose to the protagonist — but nobody else.’","A pushy sports photographer shoots her in new sneakers, which sell out as a Teisei exclusive."],
  sig:[["s","The three-legged race is a joke on the whole series: two brilliant, self-directed people tied together fall over at once. It prefigures the engagement."],["s","The villainess frame is a device she reaches for at decision points."]],
  who:["Teia Eiichi","Gotou Mitsuya"], links:["proposal","queennight"] },

{ id:"siliconvalley", d:"1998-10-30", when:"c. late 1998", basis:"est",
  t:"Silicon Valley, and a call from the Prime Minister", fig:"¥2tn",
  vol:2, ch:"Ch. 2", cat:"finance", motif:"terminal", hist:"altered",
  brief:"At the Fund’s Silicon Valley office Runa hands out anime on VHS. Fuchigami phones to ask whether Ayukawa Motors can be saved. She says no.",
  what:["Angela flies economy to tail her to a technicians’ party.","A technician begs her to fund something that exceeds the anime’s limits. Her private answer: about ten years.","Fuchigami asks about Ayukawa Motors, Japan’s second automaker, with about ¥2tn of debt.","She sees his real worry: the banks absorbing ¥2tn. He asks Keika Bank to handle small firms under the Keika Rules."],
  real:"Altered. Ayukawa Motors is Nissan, named for founder Ayukawa Yoshisuke and taken over by Renault in 1999. The glossary names the anime as Serial Experiments Lain and the future device as the iPhone.",
  who:["Fuchigami Keiichi","Angela Sullivan"], links:["sme","ltcm"] },

{ id:"queennight", d:"1998-11-21", when:"c. November 1998", basis:"est",
  t:"The Queen of the Night aria",
  vol:2, ch:"Ch. 4", cat:"personal", motif:"stage", hist:"story",
  brief:"At the culture festival Runa sings Mozart and is applauded for real. She cries: she had forgotten what praise was like.",
  what:["The class stages an opera and Runa sings the Queen of the Night aria from The Magic Flute.","Tachibana, Ichijou and Nakamaro appear unannounced.","‘I’d long since forgotten what praise was like in my previous life.’","Beforehand she tells Yuujirou she feels ‘guilty, like I’m cheating somehow’. Narration: ‘That was because I was.’","A failing opera company asks for patronage and becomes the Keika Opera Company. Tachibana admits it is partly for her protection."],
  sig:[["s","This is the volume’s emotional centre. What breaks her is being praised, which strengthens the deprivation reading over the ‘it’s all a game’ reading."]],
  who:["Izumikawa Yuujirou","Tachibana Ryuuji"], links:["concert","ninth","cry"] },

{ id:"avanti", d:"1998-12-22", when:"22 December 1998", basis:"text",
  t:"Avanti café: the 22 December ritual",
  vol:2, ch:"Ch. 4", cat:"personal", motif:"tea", hist:"story",
  brief:"The four say their pre-holiday goodbyes. Eiichi books the same table for the same date every following year.",
  what:["The Quartet meets at the Avanti café before the holidays.","Eiichi reserves the table for every 22 December to come.","Runa: ‘Dear God, even if I fall to my utter ruin, please don’t let me forget the time I spent with them.’","New Year PHS calls connect all four."],
  real:"Story event. The day is given in the novel; the year follows from the chapter’s span.",
  sig:[["p","The standing reservation is a ritual deliberately built to outlast the ruin she knows is coming."]],
  who:["Teia Eiichi","Izumikawa Yuujirou","Gotou Mitsuya"], links:["quartet","mitsuya","crash2008"] },

{ id:"sme", d:"1999-01-20", when:"c. early 1999", basis:"est",
  t:"Ichijou’s small-business rescue kit",
  vol:2, ch:"Ch. 2", cat:"finance", motif:"terminal", hist:"story",
  brief:"Banks are starving small firms. Ichijou’s answer is a two-month wall calendar, mops, snacks, 50cc scooters and cheap PCs.",
  what:["With banks racing to clean up before merging, lending to small firms dries up.","Ichijou’s diagnosis: many firms fail because their directors do not understand accounting.","A two-month wall calendar removes the blind spot of a payment due at the start of next month.","Scooters let bank staff run payment errands. Tea sets win over whoever keeps the books.","Thousands of ¥100,000 items add up to hundreds of billions, which feels like nothing next to trillions."],
  real:"Story event on a real phenomenon: Japan’s late-1990s credit crunch fell hardest on small borrowers.",
  sig:[["s","Small-firm failure is often a timing problem with working capital, not a profitability problem."],["s","Runa’s foreknowledge is useless here. Her edge does not scale downward."]],
  who:["Ichijou Susumu","Katsura Naoyuki"], links:["siliconvalley","pudding"] },

{ id:"darklink", d:"1999-02-10", when:"c. early 1999", basis:"est",
  t:"The ‘dark link’ scandal breaks",
  vol:2, ch:"Ch. 2", cat:"politics", motif:"news", hist:"story",
  brief:"The press alleges the Keika Bank auction was rigged in exchange for backing Taichirou. Someone inside the bank has leaked that the Fund is in Runa’s name.",
  what:["The Imperial Business Federation freezes the switch from book-value to market-value accounting.","At a Federation party Runa is mobbed by entertainment reporters and notices the absence of financial ones.","The opposition considers subpoenaing Vice President Izumikawa.","Ichijou vetoes planting a Far Eastern loyalist and recommends hiring cut-off ex-ministry officials."],
  reveal:["The Fund now exceeds ¥1tn, with ¥300bn hidden in Akamatsu shell companies.","Iwazaki Pharma has proposed a merger with Keika Pharmaceuticals: in effect, a takeover of the Keika Group."],
  real:"Story event. The accounting ‘big bang’ fight is real; the glossary says LTCB’s collapse triggered the reforms and that it ‘wasn’t enough warning to prevent’ Enron or Lehman.",
  sig:[["s","Market-value accounting threatens the zaibatsu’s skeleton: cross-shareholdings only work if nobody sells."]],
  who:["Izumikawa Tatsunosuke","Ichijou Susumu","Keikain Nakamaro"], links:["taichirou","testimony","governor","takenaga"] },

{ id:"testimony", d:"1999-03-03", when:"c. March 1999", basis:"est",
  t:"Nakamaro testifies in her place",
  vol:2, ch:"Ch. 2", cat:"politics", motif:"diet", hist:"story",
  brief:"Nakamaro declines to seize the Fund and volunteers to face the House of Councilors as an unsworn witness. Kiyomaro is declared her guardian.",
  what:["Nakamaro says the family’s reasonable move would be to take the Moonlight Fund, and does not take it.","He testifies as an unsworn witness, knowingly accepting public suspicion.","‘Allow me to do what a good brother should.’","Kiyomaro is publicly announced as guardian of ‘Keikain Runa, owner of the Moonlight Fund’."],
  real:"Story event on real procedure: an unsworn reference witness takes no oath, unlike a sworn Diet summons with perjury liability.",
  sig:[["s","The testimony buys time and the Tokyo election ends the scandal, as Nakamaro predicts."],["s","The guardianship plants the seed of Vol. 3’s control crisis."]],
  who:["Keikain Nakamaro","Keikain Kiyomaro"], links:["engagement","darklink","adoption"] },

{ id:"knife", d:"1999-03-16", when:"c. March 1999", basis:"est",
  t:"‘It doesn’t take a knife to silence a politician’",
  vol:2, ch:"Ch. 2", cat:"politics", motif:"ballot", hist:"story",
  brief:"With fifteen private minutes at the PM’s residence, Runa proposes ending the scandal by winning Tokyo. Then she recruits a retired novelist.",
  what:["She visits as Hokkaido’s Goodwill Ambassador of Agriculture.","‘It doesn’t take a knife to silence a politician. All it takes is an electoral victory.’","The plan: have the party’s candidate withdraw, promise post-election endorsement, and back someone nobody expects.","Iwasawa Makoto dismisses her until she offers a narrative: ‘We’re taking back the capital.’ His condition is that he may write her into a book."],
  real:"Story event. Iwasawa Makoto is Ishihara Shintarō: Akutagawa Prize novelist, former Transport Minister, with an action-star younger brother.",
  sig:[["s","A scandal is a market in attention. She does not disprove the allegation; she buries it under a bigger story."],["s","The line rejects her grandfather’s world while reproducing his method: kingmaking from behind the curtain."]],
  who:["Fuchigami Keiichi","Iwasawa Makoto"], links:["darklink","governor","lockedroom"] },

{ id:"governor", d:"1999-04-11", when:"11 April 1999", basis:"real",
  t:"Iwasawa takes the Tokyo governorship",
  vol:2, ch:"Ch. 2", cat:"politics", motif:"ballot", hist:"altered",
  brief:"Iwasawa wins in a landslide and the party endorses him afterward. The scandal collapses, and his campaign novel makes Runa a character.",
  what:["Iwasawa wins and the party endorses him after the fact.","The scandal collapses and Keika Holdings proceeds.","His novel ‘The Little Queen Takes Back the Capital’ becomes a bestseller with a film. Runa declines the lead role.","His brother’s production company warns the media off her."],
  real:"Altered. Ishihara Shintarō really won on 11 April 1999 and the LDP’s official candidate finished fourth. One change: the real incumbent, Aoshima Yukio, did not stand again.",
  sig:[["s","Runa has become a fictional character inside her own world."],["p","She will be a story, but not a performer of one."]],
  who:["Iwasawa Makoto"], links:["knife","protection","director"] },

{ id:"protection", d:"1999-05-08", when:"c. spring 1999", basis:"est",
  t:"Upstairs at the Wise Dragon King’s Palace: ‘our Little Queen’",
  vol:2, ch:"Ch. 3", cat:"shadow", motif:"spy", hist:"story",
  brief:"Fuchigami, Izumikawa and Governor Iwasawa meet in secret and arrange police protection for a girl who will never know about it.",
  what:["They toast ‘to our Little Queen’. Asked if she works for one of them: ‘Of course not. We’re the ones being used.’","They compare her to her grandfather Hikomaro, and the comparison frightens them.","Izumikawa on Katou: ‘His failure was in thinking she was a mere prop.’","¥60tn of public funds has been set aside for bad debts, with Keika Bank as the model for megabank mergers.","The Tokyo police, CIRO and the Public Safety Bureau will protect her."],
  real:"Story event. The restaurant is the real Meguro Gajoen. The proposed security chief is unmistakably Sassa Atsuyuki.",
  sig:[["s","Runa believes she is the manipulator. Two rooms of adults are managing her at the same moment."]],
  who:["Fuchigami Keiichi","Izumikawa Tatsunosuke","Iwasawa Makoto"], links:["kidnap","trustaccount","embassy"] },

{ id:"trustaccount", d:"1999-05-09", when:"c. spring 1999", basis:"est",
  t:"Downstairs: a hidden account and the Toyohara girls", fig:"¥50bn",
  vol:2, ch:"Ch. 3", cat:"shadow", motif:"vault", hist:"story",
  brief:"Tachibana, Ichijou and Toudou create a secret trust account for Runa. Toudou proposes a private intelligence service built from former child spies.",
  what:["Oil taken for Russian bonds becomes yen with no safe domestic account to hold it.","Three trust banks merge into Keika Trust Bank. Runa’s account sits in Sapporo under Katsura Naoyuki.","Toudou proposes recruiting the ‘Toyohara girls’, orphans trained as spies by Northern Japan, plus ex-Northern soldiers.","Ichijou says it sounds like human trafficking and walks out. Tachibana authorizes it in secret.","Tachibana nominates Ichijou to lead Keika Holdings."],
  reveal:["‘Her Ladyship valued the few thousand yen in her wallet much more than the billion yen in her bankbook.’","Ichijou is deliberately kept ‘pure’: ‘Leave all the dirty work to Tachibana-san and me.’"],
  sig:[["s","The book builds a protagonist who is insulated from her operation’s worst parts, not innocent of them."],["p","The Toyohara girls are set up as a moral reckoning. Five volumes in, it has not come."]],
  who:["Tachibana Ryuuji","Ichijou Susumu","Toudou Nagayoshi","Katsura Naoyuki"], links:["protection","erika","tower"] },

{ id:"megabanks", d:"1999-08-20", when:"August 1999", basis:"real",
  t:"The megabank merger wave begins",
  vol:2, ch:"Ch. 4", cat:"finance", motif:"merge", hist:"real",
  brief:"DK Bank, Fuyou and the Commercial Bank of Japan announce a three-way merger. Three more megabank mergers follow.",
  what:["DK Bank + Fuyou Bank + Commercial Bank of Japan.","Futaki Bank + Yodoyabashi Bank.","Owari Nagoya + Yamanaka.","Asahi + Osaka Nomura.","Ichijou’s arithmetic: merge three lenders and one borrower’s ¥9bn exposure sits in a single bank."],
  real:"Real. These map to Mizuho (announced August 1999), Sumitomo Mitsui, UFJ and Resona. ‘Osaka Nomura Bank’ is Daiwa Bank’s real original name.",
  sig:[["s","Consolidation turns a collective-action problem among creditors into a management decision."],["p","A merger announcement creates a deadline that forces losses to be recognized."]],
  who:["Ichijou Susumu"], links:["protection","sougou","hizen"] },

{ id:"sougou", d:"1999-09-05", when:"c. late summer 1999", basis:"est",
  t:"The Sougou–Teisei bailout merger", fig:"¥630bn",
  vol:2, ch:"Ch. 4", cat:"deals", motif:"merge", hist:"altered",
  brief:"The department-store chain most likely to fail is folded into Teisei, with ¥630bn written off. Ichijou is confirmed to head Keika Holdings.",
  what:["Sougou was the Commercial Bank of Japan’s largest source of bad debt.","The RCC spearheads the merger, ¥630bn is written off and Sougou’s managing director resigns.","Keika Bank had already sold its dangerous loans to the RCC and built reserves.","Runa tells Ichijou to build a team and choose a successor."],
  real:"Altered. Sogo really sought about ¥639bn of debt forgiveness, but the plan collapsed under public outcry and it went bankrupt in July 2000.",
  who:["Ichijou Susumu"], links:["teisei","megabanks","railway"] },

{ id:"hizen", d:"1999-11-20", when:"c. late 1999", basis:"est",
  t:"The Hizen hypermarket is saved", fig:"¥400bn",
  vol:2, ch:"Ch. 5", cat:"deals", motif:"merge", hist:"altered",
  brief:"DK Bank meant to sacrifice a hypermarket chain before its merger. Runa takes it because Hokkaido’s financial circle asked.",
  what:["Hizen carries about ¥400bn in bad debts.","It has stores in Hokkaido and goes under Teisei.","Fuchigami asks her to sing Beethoven’s Ninth in thanks."],
  real:"Altered. Hizen resembles Nagasakiya, a hypermarket chain that failed in February 2000 with debts near ¥380bn.",
  who:["Fuchigami Keiichi"], links:["megabanks","ninth"] },

{ id:"ninth", d:"1999-12-26", when:"c. late December 1999", basis:"est",
  t:"Beethoven’s Ninth: Fuchigami stumbles",
  vol:2, ch:"Ch. 5", cat:"politics", motif:"stage", hist:"altered",
  brief:"During the standing ovation the Prime Minister stumbles. Runa recognizes it at once: ‘It reminded me of the future.’",
  what:["Runa sings the Ninth at Fuchigami’s request.","He stumbles during the ovation.","She has Tachibana phone Izumikawa immediately: ‘Unless we acted, Prime Minister Fuchigami’s life was in danger.’"],
  real:"Altered. The real Obuchi suffered his stroke on 1–2 April 2000. The novel moves the warning sign to a year-end concert.",
  sig:[["s","This is the first time Runa spends foreknowledge on a person and not a position."]],
  who:["Fuchigami Keiichi","Keikain Runa"], links:["queennight","stroke"] },

{ id:"stroke", d:"2000-01-02", when:"2 January 2000", basis:"text",
  t:"Fuchigami survives his stroke and retires",
  vol:2, ch:"Ch. 5", cat:"politics", motif:"hospital", hist:"altered",
  brief:"After the Y2K non-event, Izumikawa reports that Fuchigami went to hospital on Runa’s urgent request. He lives, and must retire.",
  what:["A transient ischemic attack at the concert, compounded by chronic heart disease.","Because he was hospitalized in time, he survives.","He has been ordered to retire."],
  real:"Altered, and the volume’s largest deliberate divergence. The real Obuchi fell into a coma in April 2000 and died on 14 May 2000.",
  sig:[["s","Her foreknowledge works on individual fates, not only markets. She cannot tell whether to be pleased she saved him or upset at how his power ended."]],
  who:["Fuchigami Keiichi","Izumikawa Tatsunosuke"], links:["ninth","lockedroom","fuchigamipm"] },

{ id:"lockedroom", d:"2000-01-05", when:"c. early January 2000", basis:"est",
  t:"The locked room: ‘small kingmaker’",
  vol:2, ch:"Ch. 5", cat:"politics", motif:"hospital", hist:"altered",
  brief:"At the hospital Fuchigami admits he used her. Izumikawa asks whether he should become Prime Minister, and she tells him how.",
  what:["Hayashi, Tsurui, Murashita, Nonaka and Akagi wait with Izumikawa and Tachibana.","Fuchigami: ‘I’ll fully admit I used you. But I didn’t want you to be subpoenaed.’ He warns her off her grandfather’s path.","Izumikawa: ‘Of the people in said locked room, it is those with the money who hold the most sway.’","Her counsel: accept, declare a caretaker government, and block the leadership election until a July general election."],
  real:"Altered. The waiting room matches the ‘Gang of Five’ who chose Mori in April 2000. The names look like inversions: Hayashi = Mori, Akagi = Aoki, Murashita = Murakami, Tsurui = Kamei; Nonaka keeps his name.",
  sig:[["s","‘I used you’ is a gift of victim status. By agreeing to act as kingmaker she gives that protection up."],["s","Her warning about a no-confidence ambush is foreknowledge of the November 2000 Katō Rebellion."]],
  who:["Fuchigami Keiichi","Izumikawa Tatsunosuke","Tachibana Ryuuji"], links:["stroke","caretaker","knife","qualified"] },

{ id:"caretaker", d:"2000-01-10", e:"2000-07-25", when:"c. January – July 2000", basis:"est",
  t:"Izumikawa’s caretaker premiership",
  vol:2, ch:"Ch. 5", cat:"politics", motif:"diet", hist:"fiction",
  brief:"Izumikawa accepts a premiership he knows will last six months, ending in a summer general election. Hayashi follows him.",
  what:["A caretaker label lowers the stakes: nobody needs to topple a government that has announced its own end.","He appoints Koizumi secretary-general and hands his faction to Katou: ‘generational change’ at last.","Retired prime ministers are made counts in this world.","Hayashi, the Mori figure, takes office afterward."],
  real:"Fictional insertion. It occupies the slot of Mori’s first months; the real Mori called his election about three months after taking office.",
  sig:[["s","Stock prices are higher than they ‘should’ be in this timeline, so unrealized gains absorb bad debts. Her advantage is decaying as her remembered future drifts."]],
  who:["Izumikawa Tatsunosuke","Koizumi Souichirou","Katou Kazuhiro"], links:["lockedroom","hayashifall"] },

{ id:"railway", d:"2000-03-15", when:"c. spring 2000", basis:"est",
  t:"Keika Railway: buying the KYOSHO line", fig:"¥100bn",
  vol:2, ch:"Ch. 5", cat:"deals", motif:"train", hist:"story",
  brief:"The Fund buys a debt-laden Tokyo–Chiba line, pays off its bubble-era loans at a stroke and cuts fares. Tachibana runs the new company.",
  what:["KYOSHO Rapid Railway is bought for ¥100bn and its high-interest debt is paid off.","Fares fall and the line is rebranded under Keika Railway, with Tachibana as managing director.","The aim is a visible, respectable business core, separate from the ‘suspicious’ Moonlight Fund, before Iwazaki absorbs Keika’s old companies.","Next: the Shin-Tokiwa Railway’s unfinished extension to Tokyo."],
  real:"Story event. KYOSHO resembles the Hokusō Railway, notorious for high fares driven by construction debt. Shin-Tokiwa resembles the Tsukuba Express.",
  sig:[["s","Legitimacy is an asset. A fund is suspect; a railway is a civic institution."]],
  who:["Tachibana Ryuuji"], links:["sougou","shikoku","tvinterview"] },

{ id:"shikoku", d:"2000-05-20", when:"c. mid-2000", basis:"est",
  t:"The Shikoku Shinkansen is proposed", fig:"¥400bn",
  vol:2, ch:"Ch. 5", cat:"deals", motif:"train", hist:"altered",
  brief:"Kagawa Railroad and the Sougou store at its terminal must be saved together. Runa answers with a bullet train across the Great Seto Bridge.",
  what:["Kagawa Railroad guarantees the Sougou store’s loans, so pressing one collapses the other.","She proposes an Okayama–Takamatsu Shinkansen for about ¥400bn.","She buys Dog Express for ¥140bn to strengthen logistics under Akamatsu.","She tells Mitsuya the line will barely break even: ‘I’m after the Shikoku vote.’"],
  real:"Altered. The Shikoku Shinkansen is long proposed and never built; the bridge really was designed to carry one. Kagawa Railroad resembles Kotoden, which went bankrupt in 2001.",
  sig:[["s","Guarantee chains transmit distress sideways."],["s","The Shinkansen is a vote-buying instrument, and the vote is lost anyway in 2001."]],
  who:["Gotou Mitsuya","Toudou Nagayoshi"], links:["railway","koizumiwins","tvinterview"] },

{ id:"shotengai", d:"2000-06-20", when:"c. mid-2000", basis:"est",
  t:"The shopping districts Runa cannot fix",
  vol:2, ch:"Ch. 5", cat:"deals", motif:"news", hist:"real",
  brief:"Ichijou and Tachibana explain why reviving shopping streets is close to impossible. The detail that defeats her: shopkeepers live above their shops.",
  what:["Motorization, suburban superstores and the revised Large-Scale Retail Store Law hollowed the districts out.","Closing a shop does not free the premises, because the owner lives upstairs.","Her answer: a jointly owned convenience store and car park at each entrance, apartments to consolidate residents, and freight partnerships."],
  real:"Real problem: the hollowing-out of Japan’s regional shōtengai.",
  sig:[["p","This is the volume’s most honest failure. She has unlimited money and still cannot fix it, because the obstacle is people’s homes."]],
  who:["Ichijou Susumu","Tachibana Ryuuji"], links:["shikoku","sme"] },

{ id:"proposal", d:"2000-08-05", when:"c. 2000", basis:"est",
  t:"Eiichi proposes over breakfast",
  vol:2, ch:"Ch. 6", cat:"personal", motif:"tea", hist:"story",
  brief:"‘Making an enemy of you wouldn’t be smart.’ Eiichi proposes marriage as strategy. Runa sprays her grape juice and calls him an idiot.",
  what:["At the Teia household, Shuuichi talks hybrid cars.","Eiichi proposes: ‘This’ll be the best way to bring your answer in line with the Teia Group’s interests.’","The older Teia men roar with laughter. Nothing is decided.","Runa notes that Takanashi Mizuho will arrive on a scholarship in high school."],
  reveal:["Her irritation shows she wanted it to be otherwise."],
  real:"Story event. Teia’s hybrid work mirrors Toyota’s, whose Prius launched in 1997.",
  sig:[["p","In her world even affection arrives as a merger term."]],
  who:["Teia Eiichi"], links:["engagement","fieldday","eiichicall","crash2008"] },

{ id:"mitsuya", d:"2000-09-20", when:"c. autumn 2000", basis:"est",
  t:"Mitsuya at Avanti: ‘you’re growing up far faster than us’",
  vol:2, ch:"Ch. 6", cat:"personal", motif:"tea", hist:"story",
  brief:"Mitsuya confronts her about living like an adult. She will not let him buy her coffee: ‘I have to be able to cover costs like this for myself.’",
  what:["‘Why are you trying to cram so much into your life, Keikain? … That’s how adults live.’","‘Do you know what the three of us like least about you? … you’re growing up far faster than us.’","She refuses to let him pay for her coffee while owning a trillion yen.","She lays out a ¥400bn Shinkansen plan to a fellow grade-schooler in a café."],
  sig:[["s","The boys have diagnosed her without knowing why."],["s","Small money is real to her and large money is not. That dissociation is what permits the bets."]],
  who:["Gotou Mitsuya"], links:["avanti","shikoku","cry"] },

{ id:"tachibanahome", d:"2000-10-15", when:"c. autumn 2000", basis:"est",
  t:"Tachibana’s home: the secret",
  vol:2, ch:"Ch. 7", cat:"shadow", motif:"grave", hist:"story",
  brief:"Tachibana hires Angela away from the CIA. The last paragraph reveals that he pushed Runa’s father to suicide.",
  what:["His granddaughter Yuka, the maid of the 2008 scene, asks when he decided Runa was worth serving.","His answer is the study: a toddler who reshelves books correctly can read.","He, Ichijou and Toudou are her only real pawns, and they are losing control of what she buys.","Angela Sullivan arrives. He has outbid a Wall Street investment bank to make her Runa’s secretary."],
  reveal:["Tachibana pushed Otsumaro to suicide over the scandal and the cover-up.","He never fulfilled Hikomaro’s dying request to raise Runa as his own."],
  sig:[["s","Nakamaro’s warmth was a promise to a dying woman. Tachibana’s devotion is atonement for a killing."],["p","Runa was never the hidden player she believes herself to be. She was identified at two or three and managed ever since."]],
  who:["Tachibana Ryuuji","Tachibana Yuka","Angela Sullivan"], links:["cocom","sullivan","withdraw"] },

{ id:"iwazakirefuse", d:"2000-11-10", when:"c. late 2000", basis:"est",
  t:"Runa refuses Iwazaki",
  vol:2, ch:"Ch. 8", cat:"deals", motif:"tower", hist:"story",
  brief:"At the Choufuu Council, Iwazaki Yashirou asks her to bring all her companies and join. Sweating, she says: ‘There is still much I have left to do.’",
  what:["The Keika presidents’ council meets as Iwazaki moves to absorb the original Keika companies.","Iwazaki Yashirou, one of the zaibatsu’s three Dons, attends ‘as an observer’.","Proposed hierarchy: Keika-Iwazaki Pharma, then Keika Holdings, then Akamatsu.","Asked ‘Do you not trust us adults?’, she suppresses an immediate no."],
  real:"Story event. Iwazaki maps to Mitsubishi; the Imperial Iwazaki Bank echoes the 1996 Bank of Tokyo-Mitsubishi merger.",
  who:["Iwazaki Yashirou","Keikain Nakamaro"], links:["debut","darklink","adoption","layoffs"] },

{ id:"florida", d:"2000-11-07", e:"2000-12-12", when:"November – December 2000", basis:"real",
  t:"The US election: Florida turns red",
  vol:2, ch:"Ch. 8", cat:"world", motif:"ballot", hist:"altered",
  brief:"When the US presidential election finally resolves, Runa sighs with relief in front of Nakamaro, ‘essentially admitting my involvement’.",
  what:["The election resolves and Florida turns red.","Her relief in front of Nakamaro all but admits she was involved."],
  real:"The 2000 election and its Florida margin are real. Runa’s implied involvement is fiction.",
  who:["Keikain Nakamaro"], links:["arms"] },

{ id:"hayashifall", d:"2001-02-10", e:"2001-04-15", when:"February – April 2001", basis:"real",
  t:"The Hayashi cabinet collapses",
  vol:2, ch:"Ch. 8", cat:"politics", motif:"diet", hist:"real",
  brief:"A foundation scandal, a submarine colliding with a training ship and two lost governorships bring the government down.",
  what:["A scandal over a small-business foundation takes down Vice President Murashita and others.","A submarine collides with a training ship. Izumikawa handles it alone as Minister of Disaster Management.","Gubernatorial defeats in Chiba in March and Akita in April.","Secretary-General Nonaka withdraws his support."],
  real:"Real, closely tracked: the KSD scandal, the Ehime Maru collision of February 2001, and the fall of the Mori cabinet.",
  who:["Izumikawa Tatsunosuke"], links:["caretaker","aso"] },

{ id:"ftc", d:"2001-02-25", when:"c. early 2001", basis:"est",
  t:"The Fair Trade Commission blocks her bids",
  vol:2, ch:"Ch. 8", cat:"deals", motif:"document", hist:"story",
  brief:"Runa’s bids for a bankrupt retailer and for a convenience-store chain both fail. Money cannot buy this constraint.",
  what:["Her bid for the bankrupt Sachii fails.","Her bid for Taiei’s convenience-store division fails.","The Antimonopoly Act is described as the zaibatsu’s oldest enemy."],
  real:"Story event. Taiei resembles Daiei. The Antimonopoly Act is a real Allied postwar law; here the zaibatsu survived, so it became a permanent guerrilla war.",
  sig:[["s","The book introduces a constraint money cannot buy, and she simply loses twice."]],
  who:["Keikain Runa"], links:["sougou","layoffs"] },

{ id:"arms", d:"2001-03-12", when:"c. March 2001", basis:"est",
  t:"The Afghanistan arms report goes to Washington",
  vol:2, ch:"Ch. 8", cat:"shadow", motif:"war", hist:"story",
  brief:"The Afghan government is quietly asking Akamatsu for eastern-bloc tanks and helicopters. Runa has Angela pass the report to the United States.",
  what:["Relief supplies routed through Pakistan and India are being diverted to the Afghan government.","It secretly requests arms, ammunition, tanks and combat helicopters from Akamatsu.","Runa to Angela: ‘Make sure it’s clear what it means that this information ended up with me too.’","An ambassadorial apology over the submarine collision follows."],
  real:"Story event against real backdrops: the Bamiyan Buddhas were destroyed in March 2001.",
  sig:[["s","Her arms-trading exposure is real, and she converts it into diplomatic leverage."]],
  who:["Angela Sullivan"], links:["akamatsu","nuke","t72"] },

{ id:"aso", d:"2001-04-13", when:"c. mid-April 2001", basis:"est",
  t:"‘Political PANDEMONIUM’: the Izumikawa faction backs Aso",
  vol:2, ch:"Ch. 8", cat:"politics", motif:"news", hist:"altered",
  brief:"Runa knows Koizumi will win and cannot back him. She puts her faction behind Minister Aso, a candidate she admits cannot win.",
  what:["Koizumi runs on postal privatization, structural reform and dissolution of the zaibatsu.","Hayashi’s rules count prefectural votes first, across a week, so a landslide can eliminate a rival before Diet members vote.","Her stated reason for Aso is the Privy Council. The text flags that as a cover story.","She works the phones at Aso’s headquarters in the Shinjuku Keika Hotel."],
  reveal:["The Koizumi campaign has not bought a member register or printed pamphlets. He does not need the machinery."],
  real:"Altered. Asō Tarō really ran in 2001 and won no prefectural votes. The Izumikawa faction’s backing is fiction.",
  sig:[["x","The real Asō became Prime Minister on 24 September 2008, nine days after Lehman. Backing him may be an early investment. The dates are fact; the motive is a guess."]],
  who:["Koizumi Souichirou","Izumikawa Tatsunosuke"], links:["hayashifall","koizumiwins","crash2008"] },

{ id:"koizumiwins", d:"2001-04-23", when:"23 April 2001", basis:"text",
  t:"Koizumi wins", fig:"298–155–31",
  vol:2, ch:"Ch. 8", cat:"politics", motif:"ballot", hist:"real",
  brief:"Koizumi sweeps the prefectural votes and clinches the party leadership. Runa loses Hokkaido and Tokushima, which she had counted as her base.",
  what:["He wins Karafuto and Chishima on day one and takes Aso’s home prefecture of Fukuoka.","By day three the early favorite, Hashizume, is reported to be considering withdrawal.","Runa loses Tokushima, in Shikoku, where she built a Shinkansen to win the vote.","His cabinet breaks precedent and keeps Izumikawa as Deputy PM for crisis management."],
  real:"Real, closely tracked. Koizumi Jun’ichirō took 123 of 141 prefectural votes; the final tally was 298–155–31. The novel’s 147 prefectural votes include Karafuto and Chishima.",
  sig:[["s","His power comes from outside the locked room where Runa’s money buys influence."],["s","His ‘triangle prison of business, politics, and bureaucracy’ is where Runa lives."]],
  who:["Koizumi Souichirou","Izumikawa Tatsunosuke"], links:["aso","takenaga","fuchigamipm","qualified"] },

{ id:"takenaga", d:"2001-05-15", when:"c. May 2001", basis:"est",
  t:"Koizumi’s counterstrike: Ichijou joins his council",
  vol:2, ch:"Ch. 8", cat:"politics", motif:"tv", hist:"altered",
  brief:"Minister Takenaga argues on television for market-value accounting, naming Keika Holdings. Koizumi then offers Runa’s best man a council seat.",
  what:["Takenaga’s case: unwind cross-shareholdings and Teia could become the world’s largest carmaker.","Runa calls it ‘a request from Wall Street, a plan by a flock of vulture funds’.","Koizumi offers Ichijou a private-member seat on the Council on Economic and Fiscal Policy.","She accepts, to gain influence inside, and asks Nakamaro to join the Keika Holdings board."],
  real:"Altered. Takenaga Nobutame is Takenaka Heizō. The council is real; Ichijou’s seat is fiction.",
  sig:[["s","Both are true and the book knows it: the reform is efficiency-enhancing and it serves foreign buyers."]],
  who:["Takenaga Nobutame","Ichijou Susumu","Koizumi Souichirou"], links:["darklink","koizumiwins","bigboned","layoffs"] },

{ id:"sept11trip", d:"2001-05-26", when:"c. spring 2001", basis:"est",
  t:"‘I believe it was September 11’",
  vol:2, ch:"Ch. 8", cat:"personal", motif:"plane", hist:"story",
  brief:"Nakamaro mentions a pharmaceutical trade fair in New York. Runa asks the date.",
  what:["Nakamaro is booked to be in New York on 11 September 2001.","‘Dear God, is it really the fate of every villainess to be beset by this much despair and misfortune?’","‘And if I tried to save my cousin, meaning I couldn’t be a villainess, then… what was I?’"],
  sig:[["s","The title is ‘Cassandra’s Struggle’. Knowledge has stopped being sufficient."],["s","The villainess frame is now load-bearing identity, and saving people threatens it."]],
  who:["Keikain Nakamaro","Keikain Runa"], links:["engagement","sept11","sept12"] }
]);
