/** Event dataset, part 3: Volumes 3 to 5, and the 2008 frame scene. Field reference: events_1.js. */
window.MV_EVENTS = (window.MV_EVENTS || []).concat([

/* ───────────── Volume 3 (2001) ───────────── */
{ id:"erika", d:"2001-04-10", when:"c. spring 2001", basis:"est",
  t:"Erika is hired for talking to Runa like a person",
  vol:3, ch:"Ch. 1", cat:"personal", motif:"garden", hist:"story",
  brief:"Ichijou’s daughter tells a stranger on a department-store roof that her koi pond will get dirty. The stranger is Runa, who scouts her on the spot.",
  what:["Erika explains that koi wreck a pond’s ecosystem and proposes a biotope with rice fish.","The Keika Group holds no recruitment events; it grew by buying distressed firms and always has surplus staff.","About seventy maids on four shifts. Fifty are personal maids, mostly armed bodyguards from Kitakaba Security.","Her real job is to have tea with Runa, listen, answer back and laugh. The rooftop becomes ‘Erika’s Garden’."],
  sig:[["s","Erika is a control sample: the only person in the volume who meets Runa without knowing who she is."],["s","Runa’s companionship is now a staffed function."]],
  who:["Ichijou Erika","Ichijou Susumu"], links:["trustaccount","tower"] },

{ id:"tower", d:"2001-05-05", when:"c. spring 2001", basis:"est",
  t:"From the Den-en-chofu manor to a fortress",
  vol:3, ch:"Ch. 4 & 6", cat:"shadow", motif:"tower", hist:"story",
  brief:"Runa leaves her father’s house for Kudanshita Keika Tower: a tunnel to the police station, duplicate facilities on the roof, a Hind on standby.",
  what:["In fifth grade she takes up kendo under her maid Kitagumo Ryouko: ‘I was almost kidnapped once.’","The tower’s second basement connects to the subway and, through an unmarked iron door, to the Kudanshita police station.","Security chief Nakajima Atsushi, a former Northern captain, asks to carry weapons. She refuses: follow the law.","Three escape plans include a Hind helicopter on permanent standby, thirty minutes out."],
  real:"Story event. The armored skeleton suits are another acknowledged borrowing from Kerberos Saga.",
  sig:[["p","Leaving the manor severs the last physical link to her parents. The volume replaces it with a fortress."]],
  who:["Nakajima Atsushi","Kitagumo Ryouko"], links:["second226","erika","nuke","treasury"] },

{ id:"maidprocession", d:"2001-06-05", when:"c. 2001", basis:"est",
  t:"The Akihabara Daimyo’s Maid Procession",
  vol:3, ch:"Prologue", cat:"personal", motif:"tv", hist:"story",
  brief:"A message board watches a TV drama about Runa’s life. A poster called ‘lunakeikain’ supplies suspiciously good inside detail.",
  what:["Posters react live to ‘Imperial Guard’, a drama backed by the whole Keika Group, with Runa playing herself.","The Maid Procession: she tried to sneak into a maid café and her ex-CIA secretary answered with motorcycle outriders and sunglassed maids.","The drama shows a gunfight and an inside betrayal. The criminal organization is Russian intelligence.","Posters explain noble family laws, diplomatic immunity and the Privy Council."],
  reveal:["The glossary: noble diplomatic immunity was her grandfather’s invention. ‘Runa’s grandfather is a real demon for coming up with that idea.’"],
  sig:[["s","The camera moves outward each volume: Runa’s head, then a CIA file, then public gossip."]],
  who:["Angela Sullivan"], links:["sullivan","director","privilege"] },

{ id:"nuke", d:"2001-06-12", when:"c. early summer 2001", basis:"est",
  t:"‘They’ve got a nuke’",
  vol:3, ch:"Ch. 6", cat:"shadow", motif:"war", hist:"fiction",
  brief:"Okazaki returns from overseas with a captive’s report. Runa sends it through every channel she has: ‘This was simply too risky to keep to myself.’",
  what:["A northern alliance general’s captive says: ‘They’ve got a nuke.’","Runa distributes it to the CIA through Angela and Eva, to former Eastern intelligence through Anisha and Kitagumo, and to Tachibana.","Two 500-kiloton warheads were sold through the former Romanian secret police and vanished on a sea route.","The sponsors are identified as Libya and Iraq."],
  real:"Fictional. The nuclear-terror plot is the volume’s largest invention layered on real events.",
  sig:[["s","She shares the intelligence globally instead of trading on it."]],
  who:["Okazaki Yuuichi","Angela Sullivan","Anisha Egorova"], links:["arms","dirtybomb","sept11"] },

{ id:"bigboned", d:"2001-06-21", when:"c. June 2001", basis:"real",
  t:"‘Big-boned’ policies put her Shinkansen on the block",
  vol:3, ch:"Ch. 12", cat:"politics", motif:"diet", hist:"real",
  brief:"Koizumi’s council decides policy first and builds the budget around it, stripping the Finance Ministry of leverage.",
  what:["The Council on Economic and Fiscal Policy reverses the traditional order of policy and budget.","Runa’s Shinkansen lands on the chopping block and becomes a controversy for Minister Takenaga.","Ichijou, on the council, later offers to fund it from Keika Railway’s own money."],
  real:"Real. Koizumi’s honebuto no hōshin did invert the sequence and weaken the ministry.",
  who:["Takenaga Nobutame","Ichijou Susumu"], links:["takenaga","shikoku"] },

{ id:"spies", d:"2001-06-28", when:"c. mid-2001", basis:"est",
  t:"Rival spies at the dinner table",
  vol:3, ch:"Ch. 2", cat:"shadow", motif:"spy", hist:"story",
  brief:"Around Runa’s birthday the household gains a former Eastern agent to watch the former CIA one. The negotiated outcome is a seating plan.",
  what:["Anisha Egorova arrives: ‘more of an observer than a maid.’","Angela and Anisha refuse to look at each other.","‘Masters and servants are supposed to eat separately!’ / ‘So you want her to eat all her meals in total solitude?!’","Compromise: the original household eats with her; the intelligence staff attend without eating."],
  sig:[["s","Her home is staffed by rival intelligence services, openly. The book makes comedy of something sinister."]],
  who:["Anisha Egorova","Angela Sullivan"], links:["tachibanahome","embassy"] },

{ id:"sniper", d:"2001-07-10", when:"c. mid-2001", basis:"est",
  t:"A Chechen sniper’s target",
  vol:3, ch:"Ch. 3", cat:"shadow", motif:"spy", hist:"story",
  brief:"A Russian intelligence officer shows Director Maefuji two photographs: a Chechen sniper, and Runa.",
  what:["Maefuji, now a Director, negotiates with a Russian officer.","To explain the threat, the officer gives the full history of the Karafuto Crisis.","The glossary cites real bad-debt figures: sixteen major banks disclosed ¥18.0306tn as of March 2001."],
  real:"Story event. The Chechen War and the Kargil War are real backdrops.",
  who:["Maefuji Shouichi"], links:["karafutocrisis","kidnap"] },

{ id:"dirtybomb", d:"2001-08-18", when:"c. August 2001", basis:"est",
  t:"The Tokyo dirty bomb is stopped",
  vol:3, ch:"Ch. 6", cat:"shadow", motif:"war", hist:"fiction",
  brief:"A man is arrested in Tokyo buying precision bomb-making instruments. The plot was a diversion from targets in the US and Europe.",
  what:["A Russian citizen radicalized over the internet is arrested buying instruments.","Hardened nuclear-waste security had delayed him.","Angela: ‘we have to think of these diversion attacks as collateral damage.’","Runa knows what that means and says nothing about hijacked planes."],
  real:"Fictional. Vol. 5 adds that the detonator was being built in Akihabara.",
  sig:[["s","Intervention redistributes risk; it does not remove it."]],
  who:["Angela Sullivan","Keikain Runa"], links:["nuke","sept11","congress"] },

{ id:"tvinterview", d:"2001-08-28", when:"c. summer 2001", basis:"est",
  t:"‘And despite all that, we lost’",
  vol:3, ch:"Ch. 5", cat:"deals", motif:"tv", hist:"story",
  brief:"On television Tachibana defends Keika Railway’s spending. Okazaki Yuuichi enters as Runa’s messenger and resource buyer.",
  what:["Tachibana walks through KYOSHO, Kagawa, the Shikoku Shinkansen and the Shinjuku Shinkansen.","Pressed on political leverage: ‘railway work is a huge industry … And despite all that, we lost the presidential election.’ The room falls silent.","Okazaki, from Akamatsu’s resources department, is the man who ‘unified the Moonlight Fund and Akamatsu Corporation’."],
  sig:[["s","It is the book’s answer to charges of omnipotence. The Shinkansen was built to buy the Shikoku vote, and the vote was lost."]],
  who:["Tachibana Ryuuji","Okazaki Yuuichi"], links:["railway","shikoku","koizumiwins"] },

{ id:"general", d:"2001-09-09", when:"c. 9 September 2001", basis:"real",
  t:"The northern alliance general survives",
  vol:3, ch:"Ch. 6", cat:"world", motif:"war", hist:"altered",
  brief:"A suicide bombing fails to kill the general because Runa’s warning got protection to him in time.",
  what:["A coordinated suicide attack targets a leading northern alliance general.","He survives because of Runa’s warning."],
  real:"Altered. The real Ahmad Shah Massoud was assassinated on 9 September 2001. The novel lists his survival among the events of the 11th.",
  who:["Keikain Runa"], links:["nuke","t72"] },

{ id:"okazaki", d:"2001-09-11", when:"11 September 2001, daytime", basis:"text",
  t:"Okazaki works it out: ‘a front row seat’",
  vol:3, ch:"Ch. 6", cat:"shadow", motif:"spy", hist:"story",
  brief:"‘Your methods are too precise.’ Okazaki deduces her foreknowledge and asks only to watch her change history.",
  what:["‘Despite the threat of attacks, you’ve made no attempt to manage your assets. You’re acting to prevent terrorism under the assumption that there will be losses.’","She offers the Bamiyan Buddhas and the Gujarat earthquake as her cover story. He accepts it.","She offers him Akamatsu, billions, anything. He refuses.","‘Let me have a front row seat to see how you change history. I promise to pay for that ticket by working as your eyes and ears.’"],
  sig:[["s","Her foreknowledge is now deduced by someone inside. He trades silence for a seat."]],
  who:["Okazaki Yuuichi","Keikain Runa"], links:["sept11","wci","treasury"] },

{ id:"colorado", d:"2001-09-11", when:"11 September 2001", basis:"text",
  t:"A nuclear-waste train is hijacked in Colorado",
  vol:3, ch:"Ch. 6", cat:"world", motif:"train", hist:"fiction",
  brief:"A freight train heading for Denver is hijacked and derailed. Runa feels dread: American attention has been pulled off the East Coast.",
  what:["A freight train carrying nuclear waste is hijacked, heading for Denver.","The culprit is shot and the train is derailed.","Colorado is far from the East Coast, which is exactly the problem."],
  real:"Fictional. The glossary names Atomic Train and The Sum of All Fears as sources.",
  sig:[["s","The mobilization she caused pulled attention toward nuclear scenarios."]],
  who:["Keikain Runa"], links:["dirtybomb","sept11","congress"] },

{ id:"sept11", d:"2001-09-11", when:"11 September 2001, evening in Tokyo", basis:"text",
  t:"9/11: the Prime Minister catches her",
  vol:3, ch:"Ch. 6", cat:"world", motif:"plane", hist:"altered",
  brief:"At the tower’s completion party the second plane hits and Runa’s legs give out. Koizumi catches her: ‘What comes next is a job for adults.’",
  what:["Under cover of an approaching typhoon she has arranged nationwide disaster drills.","The party starts at 9 p.m. so that leaders can share information if anything happens.","Under the spotlight: ‘I had always longed to stand in this light in my past life, but now it was like the harsh rays of judgment.’","The second plane hits. ‘I heard something snap inside of me.’","Koizumi catches her: ‘Please rest well, and thank you for what you’ve done.’"],
  reveal:["Four planes strike, including the Pentagon and the White House."],
  real:"Altered. The Twin Towers and Pentagon strikes are real. In reality the fourth plane crashed in Pennsylvania; the novel has it hit the White House.",
  sig:[["s","‘Cassandra’s Lament’: she was believed, she mobilized nations, and it was still not enough."],["s","Her structural antagonist is the one who physically holds her up."]],
  who:["Koizumi Souichirou","Keikain Runa","Okazaki Yuuichi"], links:["sept11trip","sept12","qualified"] },

{ id:"sept12", d:"2001-09-12", when:"12 September 2001", basis:"text",
  t:"The morning after: the nightmare and the sandwiches",
  vol:3, ch:"Ch. 6", cat:"personal", motif:"grave", hist:"story",
  brief:"Runa wakes to the final count and dreams of the version she is avoiding: Nakamaro dead, the family gone, a devil’s hand taken.",
  what:["Ten hijackings were reported; six were false reports from the chaos.","Israel had concealed a stolen warhead for ten years. The US is furious.","In the nightmare her dream-self vows to save the family ‘even if I have to sell my soul to the devil’.","Nakamaro is alive, checking on every New York employee.","Yuka brings sandwiches and asks for one too: ‘our little secret’."],
  real:"Story event. Israel’s concealed warhead is fictional.",
  sig:[["x","The nightmare may be the actual mechanism of her foretold downfall, and the thing she saved Nakamaro to prevent."]],
  who:["Tachibana Yuka","Keikain Nakamaro"], links:["sept11","sept11trip","downfall"] },

{ id:"parliament", d:"2001-09-25", when:"c. late September 2001", basis:"est",
  t:"The Indian parliament is attacked",
  vol:3, ch:"Ch. 6", cat:"world", motif:"war", hist:"altered",
  brief:"An attack on India’s parliament pushes India and Pakistan toward a war that would sideline Afghanistan entirely.",
  what:["The attack pushes India and Pakistan toward war.","Japan supports US deployments to Tajikistan and Uzbekistan."],
  real:"Altered, and the author says so: in reality the attack came in December 2001. ‘In this story, the timing was perfect.’",
  who:[], links:["sept11","t72"] },

{ id:"offshore", d:"2001-10-05", when:"c. autumn 2001", basis:"est",
  t:"The Offshore Town Act",
  vol:3, ch:"Ch. 7", cat:"politics", motif:"map", hist:"fiction",
  brief:"After the attacks a contested proposal becomes law: a ten-thousand-person city at Kisarazu built from old tankers.",
  what:["Proposed by committee member Ichijou and accelerated after the attacks.","A trial city for ten thousand at Kisarazu, built from deteriorated tankers, on a ¥20bn budget.","It is aimed at Karafuto’s ‘second-class’ population, priced out of city housing."],
  real:"Fictional.",
  sig:[["p","A security crisis converts a contested proposal into law."]],
  who:["Ichijou Susumu"], links:["reunification","takenaga"] },

{ id:"t72", d:"2001-10-12", when:"c. October 2001", basis:"est",
  t:"Akamatsu arms the northern alliance", fig:"30 tanks",
  vol:3, ch:"Ch. 6", cat:"deals", motif:"war", hist:"fiction",
  brief:"Thirty T-72 tanks bought from the JSDF go to Tajikistan and across the border, with rockets, food and medicine flown in by An-124.",
  what:["Japanese PMCs are held back at US request.","Akamatsu buys thirty T-72s from the JSDF and sells them on to Tajikistan. PMCs deliver them across the border.","Anti-tank rockets, ammunition, food and medical supplies follow by chartered An-124."],
  real:"Fictional, set inside the real opening of the Afghanistan campaign.",
  who:["Toudou Nagayoshi","Okazaki Yuuichi"], links:["arms","general","saudi"] },

{ id:"cry", d:"2001-10-20", when:"c. October 2001", basis:"est",
  t:"‘It’s okay to cry’",
  vol:3, ch:"Ch. 6", cat:"personal", motif:"school", hist:"story",
  brief:"Back at school, Eiichi notices. She realizes she forgot to cry. He closes the door and she weeps.",
  what:["After a week of counseling she greets her friends normally.","‘As the person who’d been unable to stop it, what right did I have to experience such normalcy?’","Eiichi: ‘Runa, don’t push yourself so hard… It’s okay to cry.’","‘It’s okay. Now I know you’re a kid, just like the rest of us.’"],
  sig:[["s","She did not suppress grief. The category had stopped being available to her."],["p","It completes what Mitsuya began: this is the first time one of the boys finds the child in her."]],
  who:["Teia Eiichi"], links:["mitsuya","queennight","eiichicall"] },

{ id:"coup", d:"2001-10-28", when:"c. autumn 2001", basis:"est",
  t:"‘The final oligarch’",
  vol:3, ch:"Ch. 9", cat:"shadow", motif:"document", hist:"altered",
  brief:"Anisha returns from Moscow. A failed coup had wanted Runa as its centerpiece. Her staff agree on what to tell her.",
  what:["After a nuclear submarine sank, a replaced defense minister attempted a coup, funded by oligarchs and a media mogul.","The centerpiece they wanted for the new administration was Keikain Runa.","Russia’s request: ‘Don’t make your mistress the ruler of Russia or any neighboring country.’","Okazaki and Angela decide ‘what we should and shouldn’t tell the mistress’.","Iraq and Libya will price oil in euros. Angela spots a report on accounting fraud at General Energy Online."],
  real:"Altered. The Kursk sinking (August 2000) and the mogul’s flight are real. The coup is fictional. The glossary labels the petrodollar theory of the Iraq War a conspiracy theory.",
  sig:[["s","Her own staff now filter what reaches her."]],
  who:["Anisha Egorova","Okazaki Yuuichi","Angela Sullivan"], links:["moscow","geo","furukawa"] },

{ id:"fieldtrip", d:"2001-11-08", when:"c. November 2001", basis:"est",
  t:"A school trip with forty-three escorts", fig:"153 people",
  vol:3, ch:"Ch. 10–11", cat:"personal", motif:"train", hist:"story",
  brief:"Runa pays to rescue the cancelled Kyoto field trip and charters a whole Shinkansen set: 110 children and teachers, 43 guards.",
  what:["The trip was nearly cancelled after the attacks. She funds it because ‘I was the main reason for the safety risk in the first place’.","100 students, 10 teachers, 30 bodyguards, 10 maids and 3 police.","They take reserved seating so that everyone travels together.","Meanwhile Inspector Ono’s station handles a failed attack on the Shinjuku Geofront."],
  sig:[["s","She buys back one ordinary childhood experience and can only do it by militarizing it."],["s","Her existence has created a new supervisory grade in the police."]],
  who:["Keikain Runa"], links:["tower","cry"] },

{ id:"recall", d:"2001-11-15", when:"c. November 2001", basis:"est",
  t:"The Iwazaki Motors recall and the Meguro summit",
  vol:3, ch:"Ch. 12", cat:"deals", motif:"car", hist:"altered",
  brief:"A secret recall surfaces. Runa lets slip a memory of a truck’s wheel flying off, which has not happened yet.",
  what:["Eiichi corners her until she explains: departments have been doubling their books and inflating data.","The government wants to break Iwazaki Motors out of its zaibatsu and merge it with Teia Motor.","Teia cannot forget ‘Cowardly Yodoyabashi’ cutting off its funds, and has saved so much it is called ‘Teia Bank’.","A summit at the Wise Dragon King’s Palace gathers Keika, Teia, Iwazaki and Deputy PM Izumikawa."],
  real:"Altered. Iwazaki Motors is Mitsubishi Motors: the recall cover-up was exposed in 2000, and a truck wheel killed a pedestrian in 2002.",
  who:["Teia Eiichi","Iwazaki Yashirou","Izumikawa Tatsunosuke"], links:["iwazakirefuse","adoption"] },

{ id:"adoption", d:"2001-11-28", when:"c. late 2001", basis:"est",
  t:"Adopted: the Shirokane dinner",
  vol:3, ch:"Ch. 12", cat:"personal", motif:"tea", hist:"story",
  brief:"Runa is formally adopted, which makes the Fund contestable. She tests her new family and finds them sincere.",
  what:["Adoption makes Kiyomaro her legal guardian. Moves are underway to take the Moonlight Fund from her.","The instigator is the Iwazaki Corporation, with a hidden third party whispering to it. Iwazaki wants Akamatsu’s Russian crude.","Kiyomaro: ‘I don’t want to be the kind of terrible father who steals his child’s belongings.’","He sold the Keika companies to Iwazaki because the house could not staff a group that size.","Sakurako hands Runa an envelope from Iwazaki Yashirou."],
  reveal:["The binding constraint on a group is trustworthy managerial depth, not capital."],
  sig:[["s","The house set up since Vol. 1 as cold turns out to be simply decent."],["p","She loses legal autonomy at the moment she gains a family."]],
  who:["Keikain Kiyomaro","Keikain Nakamaro","Asagiri Sakurako"], links:["testimony","iwazakirefuse","trial"] },

{ id:"geo", d:"2001-12-02", when:"c. December 2001", basis:"real",
  t:"General Energy Online collapses",
  vol:3, ch:"Ch. 12", cat:"finance", motif:"chartcrash", hist:"real",
  brief:"The American energy trader behind ‘Blackship Energy’ falls to round-trip trades and off-balance-sheet debt. Runa had cancelled a deal with it, unexplained.",
  what:["Okazaki and Toudou identify round-trip transactions: firms repeating orders to each other to fake sales.","Debt from failed ventures sits in special purpose companies.","GEO lobbies to open Japan’s energy market. Runa: it wants ‘to become the dealer in Japan’s energy market casino’.","A trader recalls 9/11: the fund’s computer issued buy orders in the sell-off. ‘The computer was right.’"],
  real:"Real. GEO is Enron, which filed for bankruptcy in December 2001. ‘Blackship’ evokes Perry’s Black Ships.",
  sig:[["s","Tobashi, then mark-to-market, then round-tripping: the series argues that accounting is the load-bearing structure of capitalism."]],
  who:["Okazaki Yuuichi","Toudou Nagayoshi"], links:["ichiyama","coup","tig","wci"] },

{ id:"tig", d:"2001-12-10", when:"c. December 2001", basis:"est",
  t:"The gentlemen’s pact: TIG Systems", fig:"¥2bn",
  vol:3, ch:"Ch. 13", cat:"deals", motif:"terminal", hist:"story",
  brief:"The three boys short the collapsing company with $4m, sell their firm for ¥2bn and pick their next target.",
  what:["TIG Systems: Eiichi leads, Yuujirou runs finance and sales, Mitsuya runs technology.","A $4m short position pays off against annual revenue of ¥160m.","The portal company that gives away ADSL routers offers ¥2bn.","Eiichi: ‘we won’t be able to catch up to Runa through respectable means.’ Next target: Furukawa Telecoms."],
  real:"Story event. The portal company resembles SoftBank and Yahoo! BB’s free-modem campaign.",
  sig:[["s","The volume ends with three boys deciding how to chase someone who is not in the room."]],
  who:["Teia Eiichi","Izumikawa Yuujirou","Gotou Mitsuya"], links:["browser","geo","furukawa"] },

/* ───────────── Volume 4 (winter 2001 – spring 2002) ───────────── */
{ id:"horse", d:"2001-12-16", when:"c. mid-December 2001", basis:"real",
  t:"A racehorse that kept losing",
  vol:4, ch:"Ch. 2", cat:"personal", motif:"trophy", hist:"story",
  brief:"At the Hong Kong Vase Runa buys a horse about to retire after a career of near-misses: ‘as a villainess doomed to defeat, I couldn’t help but sympathize’.",
  what:["She flies to Sha Tin Racecourse for the Hong Kong Vase.","She meets Karl and Franz Lothringe, European aristocrats from the game’s unused backstory.","Franz: ‘Results are all that matter. That’s how it is in the world of competitions.’"],
  real:"Story event. The Hong Kong Vase is a real mid-December race.",
  sig:[["s","She buys an animal whose whole meaning is dignified losing, just before losing."]],
  who:["Keikain Runa"], links:["furukawa","qualified"] },

{ id:"memoir", d:"2001-12-22", when:"c. winter 2001–02", basis:"est",
  t:"A banker’s memoir explains 1997",
  vol:4, ch:"Ch. 1", cat:"finance", motif:"document", hist:"story",
  brief:"An ex-Far Eastern Bank man recalls the rescue from inside and supplies what Vol. 1 left out: the call market.",
  what:["Being cut off from the interbank call market is the market’s death sentence. All three 1997 firms had been cut off.","Saving only the two brokers would have turned every short seller on Hokkaido Kaitaku. They had to be saved together.","The ministry, criticized for the Jusen bailout, ‘must have seen this as a godsend’.","Keika Holdings’ politics are a mess. Frontrunner in Ichijou’s succession race: Angela Sullivan."],
  sig:[["s","Runa’s achievement is established as historically settled before the volume takes it away from her."]],
  who:["Ichijou Susumu","Angela Sullivan"], links:["sankai","keikabank","exitplan"] },

{ id:"furukawa", d:"2002-01-25", when:"c. early 2002", basis:"est",
  t:"The Furukawa Telecoms takeover: staged", fig:"33.4%",
  vol:4, ch:"Ch. 2", cat:"deals", motif:"telecom", hist:"altered",
  brief:"A hostile bid forces Runa to stand down for lack of cash. Then the viewpoint shifts: her own people arranged it.",
  what:["The Machishita Fund, backed by Iron Partners and Charles & Edward, bids for 33.4%.","Ichijou: ‘We’ll be defeated.’ The Fund’s money is in dollars and oil, and the ¥2tn Shinjuku Shinkansen was paid as a lump sum.","Runa pivots to defending Shiyo Electric.","Teikoku Telephone had got every systems developer to cancel Keika Holdings’ orders. Its one condition: ‘Get that young lady under control.’","Tachibana, Ichijou, Nakamaro and Angela manufactured the bid to make her stand down."],
  real:"Altered. Furukawa Telecoms is Fujitsu, Teikoku Telephone is NTT, Charles & Edward is Merrill Lynch, and the Machishita Fund resembles the Murakami Fund.",
  sig:[["s","A balance sheet can be enormously solvent and still lose a takeover fight, which is settled in cash on a deadline."],["s","Her guardians conspire with a hostile company and a foreign intelligence service to engineer her defeat, out of concern for her."]],
  who:["Ichijou Susumu","Tachibana Ryuuji","Keikain Nakamaro","Angela Sullivan"], links:["tig","coup","qualified","keu"] },

{ id:"wci", d:"2002-03-01", when:"c. early 2002", basis:"est",
  t:"Runa manufactures the WCI whistleblower", fig:"$400bn",
  vol:4, ch:"Ch. 2–3", cat:"finance", motif:"chartcrash", hist:"altered",
  brief:"From a London internet café, an anonymous report exposes accounting fraud at America’s second long-distance carrier. Okazaki holds the war chest.",
  what:["Okazaki has raised about $20bn of Gulf oil money at 9%, outside the Keika and Moonlight names.","It runs through the Isle of Man, the Caymans and the Virgin Islands, leveraged twenty times to $400bn.","WCI uses the same auditor as General Energy Online and is a major presidential donor.","Runa stages the reveal for Angela, knowing the CIA will route it to the White House."],
  real:"Altered. WCI is WorldCom, audited by Arthur Andersen, which collapsed in July 2002 after an internal whistleblower. Runa’s trigger is fiction.",
  sig:[["s","This is the first time she uses foreknowledge to cause a collapse instead of surviving one."],["s","The funds she burns here later chase subprime to cover their losses."]],
  who:["Okazaki Yuuichi","Angela Sullivan"], links:["geo","okazaki","subprimerefusal"] },

{ id:"kanbe", d:"2002-04-10", when:"c. spring 2002", basis:"est",
  t:"Professor Kanbe’s neoliberalism lecture",
  vol:4, ch:"Ch. 9", cat:"personal", motif:"school", hist:"story",
  brief:"‘You only have two hands.’ A professor tells a duke’s daughter that protecting the weak is how the privileged believe they are special.",
  what:["¥4m a year × 80 years × 140 million people is ¥44.8 quadrillion, against national assets of about ¥1 quadrillion.","Neoliberalism’s essence ‘is in the way it gives handicaps’: equality of opportunities and results.","Why do humans protect the weak? ‘No, it’s because we want to believe we’re special.’","‘Decide if you want to save them or force their sacrifice, then select as many of the weak as your hands can hold.’"],
  real:"Story event. The afterword names neoliberalism and ‘Koizumi theater politics’ as the volume’s subject.",
  sig:[["s","Kanbe and Koizumi make the same argument from two directions: you have two hands, and you have no mandate."]],
  who:["Professor Kanbe"], links:["qualified","erika"] },

{ id:"withdraw", d:"2002-04-25", when:"c. spring 2002", basis:"est",
  t:"‘My lady, please withdraw from Iraq’",
  vol:4, ch:"Ch. 9", cat:"shadow", motif:"war", hist:"story",
  brief:"The government is onto her Gulf preparations. Tachibana breaks with her, and Angela and Eva say nothing.",
  what:["Tachibana is targeted over Keika Railway and Ichijou over the Holdings listing. Anisha: ‘They’re only trying to cut off your own functioning limbs.’","The Cabinet Information Research Office is onto the Bahrain work.","Tachibana: ‘My lady, please withdraw from Iraq.’","Angela and Eva’s silence means the US and Japan have agreed to remove her together."],
  sig:[["s","It is the betrayal Koizumi describes, committed by people who love her."]],
  who:["Tachibana Ryuuji","Anisha Egorova","Angela Sullivan"], links:["tachibanahome","privilege","qualified","saudi"] },

{ id:"privilege", d:"2002-04-30", when:"c. spring 2002", basis:"est",
  t:"Koizumi moves to abolish noble privilege",
  vol:4, ch:"Ch. 9", cat:"politics", motif:"diet", hist:"fiction",
  brief:"Public funds for every megabank, state purchases of problem shareholdings, and a bill to outlaw nobles’ privileges in criminal cases.",
  what:["Public funds go into all major megabanks to finish bad-debt disposal.","A government system will purchase problem stock holdings.","A bill outlaws nobles’ special privileges in criminal cases.","Talks open with Russia toward a peace treaty on the Northern Karafuto Crisis."],
  real:"Mixed. The public-funds injection and the share-purchase body are real Koizumi-era measures. The privilege bill has no real equivalent.",
  sig:[["x","Abolishing the privilege may be what removes the legal instrument the game’s downfall depended on."]],
  who:["Koizumi Souichirou"], links:["normandy","maidprocession","downfall","exitplan"] },

{ id:"dream", d:"2002-05-02", when:"c. spring 2002", basis:"est",
  t:"The dream: ‘both of us are behind the times’",
  vol:4, ch:"Ch. 9", cat:"personal", motif:"school", hist:"story",
  brief:"Runa sees the game’s climax in detail for the first time. Its Runa was a reformist noble who lost a tied vote to her own fiancé.",
  what:["In high school, scholarship students drive a reform to abolish noble and zaibatsu privileges, fronted by Takanashi Mizuho.","‘Keikain Runa was a reformist despite being a noble.’ She formed a faction and sought compromise.","The vote ties. Eiichi, as president: ‘I have decided to adopt this proposal.’","‘Keikain, both of us are behind the times.’","Waking: she does not mind losing to first-rate actors. She minds losing to posterity."],
  reveal:["‘Villainess’ was never the right description. Her fear is of ‘eras of time … like gigantic waves’."],
  sig:[["s","The label she has organized her identity around is a genre convention laid over someone on the losing side of a reform she partly agreed with."]],
  who:["Teia Eiichi","Takanashi Mizuho"], links:["concert","qualified","downfall"] },

{ id:"qualified", d:"2002-05-08", when:"c. spring 2002", basis:"est",
  t:"‘You simply aren’t qualified’",
  vol:4, ch:"Ch. 9", cat:"politics", motif:"diet", hist:"story",
  brief:"At the PM’s residence Runa asks what she did wrong. Koizumi: ‘A child is trying to help kill people.’ Then he names the real defect.",
  what:["‘It’s an adult’s job to stop children when they’re heading in the wrong direction.’","‘When you fainted during the terrorist attacks and I caught you, I was shocked at how light you were.’","‘You simply aren’t qualified.’ She holds no office, no title, no command. ‘You leave everything to proxies.’","‘Even the fixers of long ago came to face the public … That’s why you’ll end up betrayed in times like these.’","He hands her a handkerchief: ‘can’t you wait a little longer?’"],
  real:"Story event. The afterword: ‘would you really make a child still in elementary school sign an order for murder?’ Koizumi is deliberately not written as a villain.",
  sig:[["s","The objection is not that she is a child or wrong. It is that she is unaccountable, and the text gives her no rebuttal."],["s","Vol. 5 reframes the defeat as a rescue."]],
  who:["Koizumi Souichirou","Keikain Runa"], links:["ledgers","sept11","lockedroom","treasury","downfall"] },

{ id:"eiichicall", d:"2002-05-09", when:"c. spring 2002", basis:"est",
  t:"Eiichi phones: ‘unless I took you down with me’",
  vol:4, ch:"Ch. 9", cat:"personal", motif:"telecom", hist:"story",
  brief:"She asks when he would betray her. He would beat up the version of himself that does, then answers honestly.",
  what:["‘You reached out to Yuujirou when everything happened last time, right? I figured it was our turn now.’","‘Right now, I’d go find the version of me that betrays you and beat him up.’","‘Still, if I had to go up against you, I’d never win unless I took you down with me.’","She realizes the dream-Eiichi’s line was addressed to her: ‘He’d gone down with me so that he could win.’"],
  sig:[["s","His canonical betrayal was mutual destruction, not abandonment."]],
  who:["Teia Eiichi"], links:["proposal","cry","dream","crash2008"] },

{ id:"saudi", d:"2002-05-24", when:"c. late spring 2002", basis:"est",
  t:"The Saudi railway is sold",
  vol:4, ch:"Ch. 12", cat:"deals", motif:"train", hist:"fiction",
  brief:"Akamatsu’s 49% of a mining railway that ends a few dozen kilometres from Iraq goes to the Americans, with Runa’s forecast priced in.",
  what:["The line runs from Dammam Port to King Khalid Military City and was rushed to 80% completion.","Her fuller plan extended it to Amman and Aqaba: ‘Baghdad departure, Jerusalem arrival.’","The PMC chief: ‘We need to be grateful that this country’s prime minister brought the boss back down to earth and scolded her.’","Okazaki: ‘She’s not well. She nearly broke down.’"],
  real:"Fictional, placed inside the real US logistics build-up before the Iraq War.",
  who:["Okazaki Yuuichi"], links:["akamatsu","t72","withdraw","treasury"] },

{ id:"exitplan", d:"2002-05-30", when:"c. late spring 2002", basis:"est",
  t:"The succession lunch: ‘the Ministries’",
  vol:4, ch:"Ch. 12", cat:"deals", motif:"tea", hist:"story",
  brief:"Ichijou tells Okazaki the exit plan and recruits him to a loyalty faction. The year’s real antagonist is named.",
  what:["Tachibana will step down before noble immunity is abolished. Ichijou will step back at the Holdings listing.","In three to five years Angela and Karin will lead. ‘Miss Angela wants to get you away from Lady Runa.’","The puppet master is ‘the Ministries’: the bureaucracies of both countries, fighting over her scattered Iraq plan.","Runa quietly holds bookkeeping, secretarial and English qualifications and is aiming at early graduation.","Ichijou: ‘Of course I do. I’m the second guy she scouted.’"],
  reveal:["She has never believed any of this was hers to keep."],
  sig:[["s","The antagonist is diffuse, non-malicious and unbeatable by acquisition."]],
  who:["Ichijou Susumu","Okazaki Yuuichi","Angela Sullivan"], links:["memoir","privilege","subprime","lunch"] },

{ id:"subprime", d:"2002-06-01", when:"c. late spring 2002", basis:"est",
  t:"‘Apparently, there are these things called subprime loans…’",
  vol:4, ch:"Ch. 12", cat:"finance", motif:"chartup", hist:"real",
  brief:"The volume’s last line. Over cold beer in 2002, two men name the mechanism that will produce 2008.",
  what:["Okazaki mentions Wall Street is up to something, with Angela involved.","Ichijou asks what.","‘Apparently, there are these things called subprime loans…’"],
  real:"Real mechanism: subprime lending drove the 2008 crisis.",
  sig:[["s","Tobashi, mark-to-market, Enron, WorldCom, subprime, Lehman. The countdown is now explicit."]],
  who:["Okazaki Yuuichi","Ichijou Susumu"], links:["ltcm","exitplan","subprimerefusal","crash2008"] },

/* ───────────── Volume 5 (summer 2002 – spring 2003) ───────────── */
{ id:"moratorium", d:"2002-06-15", e:"2003-03-31", when:"c. mid-2002 – spring 2003", basis:"est",
  t:"The Lady’s moratorium",
  vol:5, ch:"Ch. 2", cat:"personal", motif:"garden", hist:"story",
  brief:"Runa is off center stage, recovering, while the adults face the Iraq decision without her.",
  what:["She is removed from operational control and the Keika Group adapts around her absence.","Her illness ‘significantly influenced them all’.","The afterword frames the volume around anti-American sentiment and why Japan chose alignment over diplomatic independence."],
  real:"Story event. The afterword’s question: why did people choose Koizumi Jun’ichirō over Ishihara Shintarō’s route?",
  who:["Keikain Runa"], links:["qualified","treasury","teaparty"] },

{ id:"trial", d:"2002-07-15", when:"c. summer 2002", basis:"est",
  t:"A family trial in her absence",
  vol:5, ch:"Ch. 1", cat:"politics", motif:"document", hist:"story",
  brief:"The Kitayama clan demands that all Runa’s rights go to the main family. Tachibana answers with a question.",
  what:["‘Now is the time to place all her rights under the main family’s control!’","The Kitayama clan survived on the noble immunity Koizumi is about to abolish.","Kiyomaro and Nakamaro sit silent. The main family has said it will not touch her stake.","Tachibana: ‘Say you stripped her of her rights. How would you manage them?’"],
  sig:[["s","Koizumi’s lesson is tested at once: an unaccountable operator has no protection when others decide otherwise."]],
  who:["Tachibana Ryuuji","Keikain Kiyomaro","Keikain Nakamaro"], links:["adoption","privilege"] },

{ id:"keu", d:"2002-09-01", when:"1 September 2002", basis:"text",
  t:"Keika Electronics Union launches; Runa eavesdrops",
  vol:5, ch:"Ch. 2", cat:"deals", motif:"terminal", hist:"story",
  brief:"At the tower party for her new electronics group, Runa hides in a service corridor listening to guests discuss whether she is finished.",
  what:["A merger of Japanese and American computer companies creates Keika Electronics Union.","Holdings named: Shiyo Electric, Furukawa Telecoms and Portercon.","Gossip: ‘I thought she might go belly-up, given that Koizumi’s administration couldn’t stand her.’","Yuka catches her: ‘You shouldn’t be here. It’s not ladylike.’"],
  sig:[["s","She has built a tower and has no comfortable place inside it."]],
  who:["Tachibana Yuka"], links:["furukawa","layoffs"] },

{ id:"director", d:"2002-10-10", when:"c. autumn 2002", basis:"est",
  t:"The film director: ‘a natural-born actress’",
  vol:5, ch:"Ch. 3", cat:"personal", motif:"stage", hist:"story",
  brief:"A famous director found her in a rerun of the bodyguard drama. The sponsors keep refusing to let him cast her.",
  what:["‘Everyone’s got tunnel vision over her looks and singing voice … The girl is a natural-born actress.’","He drinks with an idol scout and complains about the sponsors."],
  sig:[["p","He is the third artist, after the photographer and the novelist-governor, to see Runa as raw material."]],
  who:[], links:["governor","maidprocession"] },

{ id:"lunch", d:"2002-11-18", when:"c. late 2002", basis:"est",
  t:"The megapharma threat", fig:"4 : 3 : 3",
  vol:5, ch:"Ch. 4", cat:"deals", motif:"pharma", hist:"story",
  brief:"Keika-Iwazaki merges with Hatabe at a 4:3:3 split. A foreign giant could simply buy out the other two stakes.",
  what:["Five main companies now sit at the group lunch.","Angela will become a Keika Securities director and is being groomed as CEO of Keika Holdings.","The pharma arm supplies the JSDF and US forces, who are ‘secretly stocking up’.","Nakamaro’s New York contracts, from the trip that nearly put him in Manhattan on 9/11, produced a drug America badly wants."],
  real:"Story event against the real megapharma consolidation wave. Charles & Earhart is probably Pfizer and Arts Nova probably Novartis.",
  who:["Angela Sullivan","Keikain Nakamaro"], links:["sept11trip","exitplan","subprimerefusal"] },

{ id:"subprimerefusal", d:"2002-11-22", when:"c. late 2002", basis:"est",
  t:"‘I won’t be the one who pulls that trigger’", fig:"¥30bn",
  vol:5, ch:"Ch. 4", cat:"finance", motif:"chartcrash", hist:"story",
  brief:"Angela assumes Runa will short subprime. Runa refuses. Angela: ‘Whatever you decide, my lady, that trigger is going to be pulled.’",
  what:["Angela expects the structure to ‘function until 2008’, failing through car loans.","Runa: ‘This plan will cause too much damage, though. I won’t be the one who pulls that trigger.’","The funds she burned ending the US IT bubble are now chasing subprime.","Ichijou’s compromise: ¥50bn in loans for Japanese cars only, capped at ¥30bn of a ¥100bn consortium."],
  real:"The glossary flags Angela’s error: in reality mortgages collapsed first and GM ‘caught fire from that blaze’.",
  sig:[["s","She declines the most lucrative trade available, knowing it changes nothing."],["s","Her line is not at ruthlessness or at profiting from disaster. It is at being the proximate cause."]],
  who:["Angela Sullivan","Ichijou Susumu","Keikain Runa"], links:["russia","wci","subprime","crash2008"] },

{ id:"layoffs", d:"2003-01-15", when:"c. winter 2002–03", basis:"est",
  t:"Mass layoffs; Iwazaki dissolves its own parent",
  vol:5, ch:"Ch. 6", cat:"finance", motif:"news", hist:"altered",
  brief:"In-world news: electronics makers cut tens of thousands of jobs, factories move to Karafuto, and the zaibatsu start to dissolve.",
  what:["Matsuyuki cuts 6,000, Shibaura 10,000, Somy 10,000 and the former Furukawa Telecoms 8,000. Keika Electronics Union refrains.","Factories move to Karafuto, where labor is 20% cheaper and unemployment tops 20%.","Futaki-Yodoyabashi’s cross-shareholdings are found to violate the Antitrust Act.","Iwazaki dissolves its parent company, fearing public outcry. The Nikkei slides into the ¥15,000s."],
  real:"Altered. Somy is Sony and Shibaura is Toshiba. Honami Bank sits where the real Resona did.",
  sig:[["s","The zaibatsu that survived the war dissolve anyway, through accounting rules and antitrust."]],
  who:[], links:["takenaga","ftc","iwazakirefuse","keu"] },

{ id:"congress", d:"2003-02-10", when:"c. early 2003", basis:"est",
  t:"Geneva, and a Congress in disarray",
  vol:5, ch:"Ch. 6", cat:"world", motif:"news", hist:"altered",
  brief:"Japan and Russia meet in Geneva over Karafuto. In Washington, a request for war powers reveals a plan to use nuclear weapons against Iraq.",
  what:["Japan, Russia and Britain align with the US to persuade reluctant EU states.","The president’s request covers weapons of mass destruction, revealing the nuclear plan.","The 2001 attacks are now described as diversions from the Denver train."],
  real:"Altered. The glossary also moves the London and Madrid bombings earlier, as revenge for Iraq.",
  who:[], links:["dirtybomb","colorado","treasury"] },

{ id:"embassy", d:"2003-02-25", when:"c. early 2003", basis:"est",
  t:"The US Embassy’s view: protect the girl",
  vol:5, ch:"Ch. 7", cat:"shadow", motif:"document", hist:"story",
  brief:"In a windowless room the embassy concludes that Tachibana is building structure to protect Runa, not the Keika Group.",
  what:["Eva Charon: ‘there’s no doubt that he will pick Keikain Runa over the Keika Group.’","She ‘hasn’t noticed that herself. Or rather, she’s pretended she hasn’t noticed it all this time.’","The former Northern intelligence network and the ex-KGB have formed a faction inside the Keika Group."],
  sig:[["s","She is at once the most surveilled and the most sheltered person in the book."]],
  who:["Eva Charon","Yulia Molotova","Tachibana Ryuuji"], links:["protection","spies","teaparty"] },

{ id:"treasury", d:"2003-03-20", e:"2003-04-15", when:"20 March 2003", basis:"text",
  t:"March 20: the war begins", fig:"¥10tn",
  vol:5, ch:"Ch. 5", cat:"world", motif:"vault", hist:"real",
  brief:"In the treasury under her tower Okazaki tells her: ‘It’s started.’ Then he names what broke her.",
  what:["The underground treasury holds over ¥10tn. In the front room sits the single ¥100m she stared at as a child.","‘You broke because you realized you were capable of something so disgusting.’","Her plan had embraced US nuclear strikes killing millions as deterrence. She had named Fallujah.","It does not happen. ‘This world is so foolish and so kind.’","The war ends within a month."],
  real:"The invasion of Iraq on 20 March 2003 is real. The nuclear plan is a severe counterfactual and clearly marked as alternate history.",
  sig:[["s","Koizumi’s ‘a child is trying to help kill people’ was not hyperbole."],["s","She did not break from horror at the world. She broke on discovering what she could propose."]],
  who:["Okazaki Yuuichi","Keikain Runa"], links:["qualified","okazaki","saudi","congress"] },

{ id:"fortune", d:"2003-03-25", when:"c. March 2003", basis:"est",
  t:"Graduation, and a fortune teller",
  vol:5, ch:"Ch. 8", cat:"shadow", motif:"dollhouse", hist:"story",
  brief:"Elementary school ends. Classmates diagnose Runa, and the Kanna family’s fortune tellers enter.",
  what:["Mio gives Runa a bouquet. Hotaru appears ‘in full form and smiling’.","Classmates: ‘you get good academic scores, but you don’t take anything seriously all the way through.’","Kanna Mizuki is introduced."],
  sig:[["p","This is the third unexplained supernatural thread, after Hotaru and the dollhouse."]],
  who:["Kanna Mizuki","Kaihouin Hotaru","Amane Mio"], links:["dollhouse","teaparty"] },

{ id:"teaparty", d:"2003-04-12", when:"c. April 2003", basis:"est",
  t:"The Queen Bee’s tea party", fig:"69 girls",
  vol:5, ch:"Ch. 9", cat:"personal", motif:"tea", hist:"story",
  brief:"Runa builds her junior-high faction of sixty-nine girls. Nozuki: ‘You already lead plenty of guild battles here in real life.’",
  what:["Kushunnai Nanami leads the faction and doubles as her body double. Nozuki Misaki advises.","Several members are ‘temporary workers sent to me with strings attached by the superpowers’.","59 of the 69 come from her own class of 100.","Mio arrives as a queen bee in her own right, leading an independent faction."],
  who:["Kushunnai Nanami","Nozuki Misaki","Amane Mio"], links:["embassy","fortune","downfall"] },

{ id:"downfall", d:"2003-04-13", when:"c. April 2003", basis:"est",
  t:"The downfall, solved: ‘Poor Keikain Runa’",
  vol:5, ch:"Ch. 9", cat:"shadow", motif:"map", hist:"story",
  brief:"Cleaning up after the party, Runa finally sees how the game’s villainess fell: a Karafuto tax and law haven that collapsed with 2008.",
  what:["Mio and Lydia were never in the game.","The game’s Runa, as ducal heir: ‘So I’m going to turn Karafuto into a special economic zone serving as a tax haven and law haven…’","Money laundering under noble privilege. Eiichi for finance, Yuujirou for politicians, Mitsuya for tax.","‘I’d become the adult Prime Minister Koizumi kept me from becoming when he scolded me.’","Hotaru takes her hand. The last line, silent: ‘Poor Keikain Runa.’"],
  reveal:["The ruin was an unromantic financial scheme that depended on the very privilege Koizumi is abolishing."],
  sig:[["s","The otome frame is fully dismantled, and the Vol. 4 defeat becomes the most protective act anyone has performed for her."],["x","‘Poor Keikain Runa’ may mark her beginning to separate herself from the original."]],
  who:["Keikain Runa","Kaihouin Hotaru","Kanna Mizuki"], links:["dream","qualified","privilege","crash2008"] },

/* ───────────── The frame ───────────── */
{ id:"crash2008", d:"2008-09-15", when:"15 September 2008", basis:"text",
  t:"September 15th, 2008: Lehthan Sisters falls",
  vol:1, ch:"Ch. 1", cat:"finance", motif:"chartcrash", hist:"real",
  brief:"The frame scene. At a Teia Tower party in Daiba, eighteen-year-old Runa is confronted by her fiancé and ends the engagement herself.",
  what:["Runa, 18, attends a Teia Group celebration at the Teia Tower in Daiba.","Teia Eiichi confronts her coldly over unexplained financial activity.","News breaks that ‘Lehthan Sisters’ has filed for Chapter 11.","Takanashi Mizuho bursts in with Mitsuya and Yuujirou, upset that Runa never asked for help.","She ends the engagement on her own terms and walks out past her maid, Tachibana Yuka."],
  real:"Real. The glossary: ‘The date that the Lehman Brothers go bankrupt in the real world.’",
  sig:[["s","‘Before the Crash’ in the title is a literal countdown. Everything else rewinds and moves toward this night."],["s","The series’ central open question: does the downfall still happen once noble privilege is abolished?"]],
  who:["Keikain Runa","Teia Eiichi","Takanashi Mizuho","Tachibana Yuka"], links:["birth","ltcm","subprime","downfall"] }
]);
